// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: cm/server/v1/server.proto

// Package cm.server.v1 is the interface clients use. The server is the only entry point:
// clients never talk to a shim directly.
//
// Unlike the shim API, this surface may evolve. A client and server are upgraded
// together, and a client that meets an incompatible server can simply refuse to attach
// with a clear message.

package serverv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// SessionState is a session's lifecycle stage.
type SessionState int32

const (
	SessionState_SESSION_STATE_UNSPECIFIED SessionState = 0
	// The session has a live shim holding a running shell.
	SessionState_SESSION_STATE_RUNNING SessionState = 1
	// The shell exited, and exit_code says with what.
	SessionState_SESSION_STATE_EXITED SessionState = 2
	// The shim could not be reached. Distinct from exited because the outcome is unknown rather
	// than observed, so exit_code means nothing.
	SessionState_SESSION_STATE_DEAD SessionState = 3
)

// Enum value maps for SessionState.
var (
	SessionState_name = map[int32]string{
		0: "SESSION_STATE_UNSPECIFIED",
		1: "SESSION_STATE_RUNNING",
		2: "SESSION_STATE_EXITED",
		3: "SESSION_STATE_DEAD",
	}
	SessionState_value = map[string]int32{
		"SESSION_STATE_UNSPECIFIED": 0,
		"SESSION_STATE_RUNNING":     1,
		"SESSION_STATE_EXITED":      2,
		"SESSION_STATE_DEAD":        3,
	}
)

func (x SessionState) Enum() *SessionState {
	p := new(SessionState)
	*p = x
	return p
}

func (x SessionState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SessionState) Descriptor() protoreflect.EnumDescriptor {
	return file_cm_server_v1_server_proto_enumTypes[0].Descriptor()
}

func (SessionState) Type() protoreflect.EnumType {
	return &file_cm_server_v1_server_proto_enumTypes[0]
}

func (x SessionState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SessionState.Descriptor instead.
func (SessionState) EnumDescriptor() ([]byte, []int) {
	return file_cm_server_v1_server_proto_rawDescGZIP(), []int{0}
}

// HistoryFormat selects how session contents are rendered.
type HistoryFormat int32

const (
	// Plain text, suitable for piping to a file or a pager.
	HistoryFormat_HISTORY_FORMAT_UNSPECIFIED HistoryFormat = 0
	// Escape sequences, preserving colors and styling.
	HistoryFormat_HISTORY_FORMAT_VT HistoryFormat = 1
	// HTML, preserving styling.
	HistoryFormat_HISTORY_FORMAT_HTML HistoryFormat = 2
)

// Enum value maps for HistoryFormat.
var (
	HistoryFormat_name = map[int32]string{
		0: "HISTORY_FORMAT_UNSPECIFIED",
		1: "HISTORY_FORMAT_VT",
		2: "HISTORY_FORMAT_HTML",
	}
	HistoryFormat_value = map[string]int32{
		"HISTORY_FORMAT_UNSPECIFIED": 0,
		"HISTORY_FORMAT_VT":          1,
		"HISTORY_FORMAT_HTML":        2,
	}
)

func (x HistoryFormat) Enum() *HistoryFormat {
	p := new(HistoryFormat)
	*p = x
	return p
}

func (x HistoryFormat) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (HistoryFormat) Descriptor() protoreflect.EnumDescriptor {
	return file_cm_server_v1_server_proto_enumTypes[1].Descriptor()
}

func (HistoryFormat) Type() protoreflect.EnumType {
	return &file_cm_server_v1_server_proto_enumTypes[1]
}

func (x HistoryFormat) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use HistoryFormat.Descriptor instead.
func (HistoryFormat) EnumDescriptor() ([]byte, []int) {
	return file_cm_server_v1_server_proto_rawDescGZIP(), []int{1}
}

// ShutdownRequest asks the server to stop.
type ShutdownRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShutdownRequest) Reset() {
	*x = ShutdownRequest{}
	mi := &file_cm_server_v1_server_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShutdownRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShutdownRequest) ProtoMessage() {}

func (x *ShutdownRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cm_server_v1_server_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShutdownRequest.ProtoReflect.Descriptor instead.
func (*ShutdownRequest) Descriptor() ([]byte, []int) {
	return file_cm_server_v1_server_proto_rawDescGZIP(), []int{0}
}

// ShutdownResponse confirms the server is stopping.
type ShutdownResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShutdownResponse) Reset() {
	*x = ShutdownResponse{}
	mi := &file_cm_server_v1_server_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShutdownResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShutdownResponse) ProtoMessage() {}

func (x *ShutdownResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cm_server_v1_server_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShutdownResponse.ProtoReflect.Descriptor instead.
func (*ShutdownResponse) Descriptor() ([]byte, []int) {
	return file_cm_server_v1_server_proto_rawDescGZIP(), []int{1}
}

// AttachRequest is a client-to-server event. The first message on the stream must be an
// Open; everything after it is input, a resize, or a detach.
type AttachRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Event:
	//
	//	*AttachRequest_Open
	//	*AttachRequest_Input
	//	*AttachRequest_Resize
	//	*AttachRequest_Detach
	Event         isAttachRequest_Event `protobuf_oneof:"event"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AttachRequest) Reset() {
	*x = AttachRequest{}
	mi := &file_cm_server_v1_server_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttachRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttachRequest) ProtoMessage() {}

func (x *AttachRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cm_server_v1_server_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttachRequest.ProtoReflect.Descriptor instead.
func (*AttachRequest) Descriptor() ([]byte, []int) {
	return file_cm_server_v1_server_proto_rawDescGZIP(), []int{2}
}

func (x *AttachRequest) GetEvent() isAttachRequest_Event {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *AttachRequest) GetOpen() *Open {
	if x != nil {
		if x, ok := x.Event.(*AttachRequest_Open); ok {
			return x.Open
		}
	}
	return nil
}

func (x *AttachRequest) GetInput() *Input {
	if x != nil {
		if x, ok := x.Event.(*AttachRequest_Input); ok {
			return x.Input
		}
	}
	return nil
}

func (x *AttachRequest) GetResize() *Resize {
	if x != nil {
		if x, ok := x.Event.(*AttachRequest_Resize); ok {
			return x.Resize
		}
	}
	return nil
}

func (x *AttachRequest) GetDetach() *Detach {
	if x != nil {
		if x, ok := x.Event.(*AttachRequest_Detach); ok {
			return x.Detach
		}
	}
	return nil
}

type isAttachRequest_Event interface {
	isAttachRequest_Event()
}

type AttachRequest_Open struct {
	Open *Open `protobuf:"bytes,1,opt,name=open,proto3,oneof"`
}

type AttachRequest_Input struct {
	Input *Input `protobuf:"bytes,2,opt,name=input,proto3,oneof"`
}

type AttachRequest_Resize struct {
	Resize *Resize `protobuf:"bytes,3,opt,name=resize,proto3,oneof"`
}

type AttachRequest_Detach struct {
	Detach *Detach `protobuf:"bytes,4,opt,name=detach,proto3,oneof"`
}

func (*AttachRequest_Open) isAttachRequest_Event() {}

func (*AttachRequest_Input) isAttachRequest_Event() {}

func (*AttachRequest_Resize) isAttachRequest_Event() {}

func (*AttachRequest_Detach) isAttachRequest_Event() {}

type Open struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Session to attach to. Empty asks the server to allocate a unique name, which is how
	// a terminal emulator creates a per-window session without inventing names itself.
	Session string `protobuf:"bytes,1,opt,name=session,proto3" json:"session,omitempty"`
	// Initial window size.
	Rows   uint32 `protobuf:"varint,2,opt,name=rows,proto3" json:"rows,omitempty"`
	Cols   uint32 `protobuf:"varint,3,opt,name=cols,proto3" json:"cols,omitempty"`
	XPixel uint32 `protobuf:"varint,4,opt,name=x_pixel,json=xPixel,proto3" json:"x_pixel,omitempty"`
	YPixel uint32 `protobuf:"varint,5,opt,name=y_pixel,json=yPixel,proto3" json:"y_pixel,omitempty"`
	// Resume output from this sequence number instead of restoring screen state. Set by a
	// client reconnecting after the server restarted: its terminal still shows the session,
	// so it wants the bytes it missed, not a fresh repaint. Absent on a first attach.
	ResumeFromSeq *uint64 `protobuf:"varint,6,opt,name=resume_from_seq,json=resumeFromSeq,proto3,oneof" json:"resume_from_seq,omitempty"`
	// Take ownership of the session: if this client's connection drops without sending a
	// Detach, the server terminates the session.
	//
	// This is what makes per-window sessions work without external cleanup. Closing a
	// terminal window kills its session, while detaching deliberately, or the server
	// restarting, leaves it running. Distinguishing those cases is exactly what a terminal
	// emulator cannot do reliably from the outside.
	Own bool `protobuf:"varint,7,opt,name=own,proto3" json:"own,omitempty"`
	// Attach without sending input or affecting sizing: a read-only follower.
	ReadOnly bool `protobuf:"varint,8,opt,name=read_only,json=readOnly,proto3" json:"read_only,omitempty"`
	// Command to run instead of the user's shell. Only meaningful when creating.
	Command []string `protobuf:"bytes,9,rep,name=command,proto3" json:"command,omitempty"`
	// Working directory for a newly created session. Empty means the client's cwd.
	Cwd string `protobuf:"bytes,10,opt,name=cwd,proto3" json:"cwd,omitempty"`
	// Environment variables to set for a newly created session, as KEY=VALUE.
	Env []string `protobuf:"bytes,11,rep,name=env,proto3" json:"env,omitempty"`
	// Terminal-related variables from this client's own environment, as KEY -> VALUE.
	//
	// Recorded on every attach, not just creation. A shell in a long-lived session holds values
	// describing the terminal that started it, and reattaching from a new terminal, or the same
	// one after it restarted, makes those stale. kitty's KITTY_LISTEN_ON is the sharp case, since
	// every kitten call goes through it.
	//
	// Distinct from env above, which sets variables for a shell being created. These are recorded
	// for an existing shell to ask about later.
	ClientEnv map[string]string `protobuf:"bytes,12,rep,name=client_env,json=clientEnv,proto3" json:"client_env,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Persist requests that this session's content survive a reboot, regardless of whether its name
	// matches the server's configured patterns.
	Persist bool `protobuf:"varint,13,opt,name=persist,proto3" json:"persist,omitempty"`
	// OnRestore overrides the server's configured behavior when reviving this session: "shell",
	// "none", or "command". Empty means the configured default.
	//
	// A string rather than an enum because it is a per-session override of a config value that is
	// also a string, and keeping one spelling avoids two vocabularies for the same setting.
	OnRestore string `protobuf:"bytes,14,opt,name=on_restore,json=onRestore,proto3" json:"on_restore,omitempty"`
	// CaptureOutput saves this session's output so it can be read after the session ends, without
	// asking for reboot survival.
	//
	// Distinct from persist because the two differ in how long the session is kept, not in mechanism.
	// `cm run` sets this so `cm history` works once the command has exited, while leaving the session
	// eligible for prompt cleanup rather than the week a persisted session is kept.
	CaptureOutput bool `protobuf:"varint,15,opt,name=capture_output,json=captureOutput,proto3" json:"capture_output,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Open) Reset() {
	*x = Open{}
	mi := &file_cm_server_v1_server_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Open) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Open) ProtoMessage() {}

func (x *Open) ProtoReflect() protoreflect.Message {
	mi := &file_cm_server_v1_server_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Open.ProtoReflect.Descriptor instead.
func (*Open) Descriptor() ([]byte, []int) {
	return file_cm_server_v1_server_proto_rawDescGZIP(), []int{3}
}

func (x *Open) GetSession() string {
	if x != nil {
		return x.Session
	}
	return ""
}

func (x *Open) GetRows() uint32 {
	if x != nil {
		return x.Rows
	}
	return 0
}

func (x *Open) GetCols() uint32 {
	if x != nil {
		return x.Cols
	}
	return 0
}

func (x *Open) GetXPixel() uint32 {
	if x != nil {
		return x.XPixel
	}
	return 0
}

func (x *Open) GetYPixel() uint32 {
	if x != nil {
		return x.YPixel
	}
	return 0
}

func (x *Open) GetResumeFromSeq() uint64 {
	if x != nil && x.ResumeFromSeq != nil {
		return *x.ResumeFromSeq
	}
	return 0
}

func (x *Open) GetOwn() bool {
	if x != nil {
		return x.Own
	}
	return false
}

func (x *Open) GetReadOnly() bool {
	if x != nil {
		return x.ReadOnly
	}
	return false
}

func (x *Open) GetCommand() []string {
	if x != nil {
		return x.Command
	}
	return nil
}

func (x *Open) GetCwd() string {
	if x != nil {
		return x.Cwd
	}
	return ""
}

func (x *Open) GetEnv() []string {
	if x != nil {
		return x.Env
	}
	return nil
}

func (x *Open) GetClientEnv() map[string]string {
	if x != nil {
		return x.ClientEnv
	}
	return nil
}

func (x *Open) GetPersist() bool {
	if x != nil {
		return x.Persist
	}
	return false
}

func (x *Open) GetOnRestore() string {
	if x != nil {
		return x.OnRestore
	}
	return ""
}

func (x *Open) GetCaptureOutput() bool {
	if x != nil {
		return x.CaptureOutput
	}
	return false
}

type Input struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Input) Reset() {
	*x = Input{}
	mi := &file_cm_server_v1_server_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Input) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Input) ProtoMessage() {}

func (x *Input) ProtoReflect() protoreflect.Message {
	mi := &file_cm_server_v1_server_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Input.ProtoReflect.Descriptor instead.
func (*Input) Descriptor() ([]byte, []int) {
	return file_cm_server_v1_server_proto_rawDescGZIP(), []int{4}
}

func (x *Input) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type Resize struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rows          uint32                 `protobuf:"varint,1,opt,name=rows,proto3" json:"rows,omitempty"`
	Cols          uint32                 `protobuf:"varint,2,opt,name=cols,proto3" json:"cols,omitempty"`
	XPixel        uint32                 `protobuf:"varint,3,opt,name=x_pixel,json=xPixel,proto3" json:"x_pixel,omitempty"`
	YPixel        uint32                 `protobuf:"varint,4,opt,name=y_pixel,json=yPixel,proto3" json:"y_pixel,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Resize) Reset() {
	*x = Resize{}
	mi := &file_cm_server_v1_server_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Resize) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Resize) ProtoMessage() {}

func (x *Resize) ProtoReflect() protoreflect.Message {
	mi := &file_cm_server_v1_server_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Resize.ProtoReflect.Descriptor instead.
func (*Resize) Descriptor() ([]byte, []int) {
	return file_cm_server_v1_server_proto_rawDescGZIP(), []int{5}
}

func (x *Resize) GetRows() uint32 {
	if x != nil {
		return x.Rows
	}
	return 0
}

func (x *Resize) GetCols() uint32 {
	if x != nil {
		return x.Cols
	}
	return 0
}

func (x *Resize) GetXPixel() uint32 {
	if x != nil {
		return x.XPixel
	}
	return 0
}

func (x *Resize) GetYPixel() uint32 {
	if x != nil {
		return x.YPixel
	}
	return 0
}

// Detach ends this client's attachment without terminating the session. Sending it
// explicitly is what distinguishes leaving a session from losing the connection, so an
// owning client's session survives a deliberate detach.
type Detach struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Detach) Reset() {
	*x = Detach{}
	mi := &file_cm_server_v1_server_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Detach) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Detach) ProtoMessage() {}

func (x *Detach) ProtoReflect() protoreflect.Message {
	mi := &file_cm_server_v1_server_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Detach.ProtoReflect.Descriptor instead.
func (*Detach) Descriptor() ([]byte, []int) {
	return file_cm_server_v1_server_proto_rawDescGZIP(), []int{6}
}

// AttachResponse is a server-to-client event.
type AttachResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Event:
	//
	//	*AttachResponse_Opened
	//	*AttachResponse_Output
	//	*AttachResponse_Exited
	//	*AttachResponse_Metadata
	//	*AttachResponse_Detached
	Event         isAttachResponse_Event `protobuf_oneof:"event"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AttachResponse) Reset() {
	*x = AttachResponse{}
	mi := &file_cm_server_v1_server_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttachResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttachResponse) ProtoMessage() {}

func (x *AttachResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cm_server_v1_server_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttachResponse.ProtoReflect.Descriptor instead.
func (*AttachResponse) Descriptor() ([]byte, []int) {
	return file_cm_server_v1_server_proto_rawDescGZIP(), []int{7}
}

func (x *AttachResponse) GetEvent() isAttachResponse_Event {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *AttachResponse) GetOpened() *Opened {
	if x != nil {
		if x, ok := x.Event.(*AttachResponse_Opened); ok {
			return x.Opened
		}
	}
	return nil
}

func (x *AttachResponse) GetOutput() *Output {
	if x != nil {
		if x, ok := x.Event.(*AttachResponse_Output); ok {
			return x.Output
		}
	}
	return nil
}

func (x *AttachResponse) GetExited() *Exited {
	if x != nil {
		if x, ok := x.Event.(*AttachResponse_Exited); ok {
			return x.Exited
		}
	}
	return nil
}

func (x *AttachResponse) GetMetadata() *Metadata {
	if x != nil {
		if x, ok := x.Event.(*AttachResponse_Metadata); ok {
			return x.Metadata
		}
	}
	return nil
}

func (x *AttachResponse) GetDetached() *Detached {
	if x != nil {
		if x, ok := x.Event.(*AttachResponse_Detached); ok {
			return x.Detached
		}
	}
	return nil
}

type isAttachResponse_Event interface {
	isAttachResponse_Event()
}

type AttachResponse_Opened struct {
	Opened *Opened `protobuf:"bytes,1,opt,name=opened,proto3,oneof"`
}

type AttachResponse_Output struct {
	Output *Output `protobuf:"bytes,2,opt,name=output,proto3,oneof"`
}

type AttachResponse_Exited struct {
	Exited *Exited `protobuf:"bytes,3,opt,name=exited,proto3,oneof"`
}

type AttachResponse_Metadata struct {
	Metadata *Metadata `protobuf:"bytes,4,opt,name=metadata,proto3,oneof"`
}

type AttachResponse_Detached struct {
	Detached *Detached `protobuf:"bytes,5,opt,name=detached,proto3,oneof"`
}

func (*AttachResponse_Opened) isAttachResponse_Event() {}

func (*AttachResponse_Output) isAttachResponse_Event() {}

func (*AttachResponse_Exited) isAttachResponse_Event() {}

func (*AttachResponse_Metadata) isAttachResponse_Event() {}

func (*AttachResponse_Detached) isAttachResponse_Event() {}

// Detached confirms the server processed a client's Detach.
//
// A client must wait for this before exiting. Sending Detach and returning immediately does not work:
// the send is asynchronous, so the connection is torn down before the message is transmitted, and the
// server then sees a client that vanished without detaching. For an owned session that means being
// destroyed, which is the opposite of what detaching asks for.
type Detached struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Detached) Reset() {
	*x = Detached{}
	mi := &file_cm_server_v1_server_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Detached) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Detached) ProtoMessage() {}

func (x *Detached) ProtoReflect() protoreflect.Message {
	mi := &file_cm_server_v1_server_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Detached.ProtoReflect.Descriptor instead.
func (*Detached) Descriptor() ([]byte, []int) {
	return file_cm_server_v1_server_proto_rawDescGZIP(), []int{8}
}

// Metadata reports what the shell has said about itself, so a client can act on it.
//
// A terminal emulator needs this: retitling a tab, or opening a new window in the session's
// directory, requires knowing values that the shell reported to the multiplexer rather than to the
// terminal. Sent on attach and whenever a value changes.
type Metadata struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Title string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	// Working directory, decoded from OSC 7 rather than the raw URI the shell sent.
	Cwd string `protobuf:"bytes,2,opt,name=cwd,proto3" json:"cwd,omitempty"`
	// Whether cwd exists on the client's machine. False once a session has ssh'd elsewhere, in
	// which case acting on the path locally is wrong.
	CwdIsLocal    bool `protobuf:"varint,3,opt,name=cwd_is_local,json=cwdIsLocal,proto3" json:"cwd_is_local,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Metadata) Reset() {
	*x = Metadata{}
	mi := &file_cm_server_v1_server_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Metadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Metadata) ProtoMessage() {}

func (x *Metadata) ProtoReflect() protoreflect.Message {
	mi := &file_cm_server_v1_server_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Metadata.ProtoReflect.Descriptor instead.
func (*Metadata) Descriptor() ([]byte, []int) {
	return file_cm_server_v1_server_proto_rawDescGZIP(), []int{9}
}

func (x *Metadata) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Metadata) GetCwd() string {
	if x != nil {
		return x.Cwd
	}
	return ""
}

func (x *Metadata) GetCwdIsLocal() bool {
	if x != nil {
		return x.CwdIsLocal
	}
	return false
}

type Opened struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Resolved session name, which the client needs when it asked the server to allocate
	// one.
	Session string `protobuf:"bytes,1,opt,name=session,proto3" json:"session,omitempty"`
	// Whether this call created the session.
	Created bool `protobuf:"varint,2,opt,name=created,proto3" json:"created,omitempty"`
	// Bytes to write to the terminal before streaming output: either serialized screen
	// state on a fresh attach, or nothing when resuming.
	Restore []byte `protobuf:"bytes,3,opt,name=restore,proto3" json:"restore,omitempty"`
	// Sequence number the following output stream starts at. A client tracks this so it can
	// resume from the right place after a reconnect.
	NextSeq       uint64 `protobuf:"varint,4,opt,name=next_seq,json=nextSeq,proto3" json:"next_seq,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Opened) Reset() {
	*x = Opened{}
	mi := &file_cm_server_v1_server_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Opened) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Opened) ProtoMessage() {}

func (x *Opened) ProtoReflect() protoreflect.Message {
	mi := &file_cm_server_v1_server_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Opened.ProtoReflect.Descriptor instead.
func (*Opened) Descriptor() ([]byte, []int) {
	return file_cm_server_v1_server_proto_rawDescGZIP(), []int{10}
}

func (x *Opened) GetSession() string {
	if x != nil {
		return x.Session
	}
	return ""
}

func (x *Opened) GetCreated() bool {
	if x != nil {
		return x.Created
	}
	return false
}

func (x *Opened) GetRestore() []byte {
	if x != nil {
		return x.Restore
	}
	return nil
}

func (x *Opened) GetNextSeq() uint64 {
	if x != nil {
		return x.NextSeq
	}
	return 0
}

type Output struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Seq   uint64                 `protobuf:"varint,1,opt,name=seq,proto3" json:"seq,omitempty"`
	Data  []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	// Set when output was truncated before the requested sequence, so the client knows its
	// view has a hole and should reattach fresh rather than assume continuity.
	Gap           bool `protobuf:"varint,3,opt,name=gap,proto3" json:"gap,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Output) Reset() {
	*x = Output{}
	mi := &file_cm_server_v1_server_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Output) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Output) ProtoMessage() {}

func (x *Output) ProtoReflect() protoreflect.Message {
	mi := &file_cm_server_v1_server_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Output.ProtoReflect.Descriptor instead.
func (*Output) Descriptor() ([]byte, []int) {
	return file_cm_server_v1_server_proto_rawDescGZIP(), []int{11}
}

func (x *Output) GetSeq() uint64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *Output) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *Output) GetGap() bool {
	if x != nil {
		return x.Gap
	}
	return false
}

// Exited reports that the session's shell exited, so the client should stop rather than
// try to reconnect.
type Exited struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExitCode      int32                  `protobuf:"varint,1,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Exited) Reset() {
	*x = Exited{}
	mi := &file_cm_server_v1_server_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Exited) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Exited) ProtoMessage() {}

func (x *Exited) ProtoReflect() protoreflect.Message {
	mi := &file_cm_server_v1_server_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Exited.ProtoReflect.Descriptor instead.
func (*Exited) Descriptor() ([]byte, []int) {
	return file_cm_server_v1_server_proto_rawDescGZIP(), []int{12}
}

func (x *Exited) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

type ListRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Only sessions whose name matches this prefix. Empty matches all.
	Prefix        string `protobuf:"bytes,1,opt,name=prefix,proto3" json:"prefix,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRequest) Reset() {
	*x = ListRequest{}
	mi := &file_cm_server_v1_server_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRequest) ProtoMessage() {}

func (x *ListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cm_server_v1_server_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRequest.ProtoReflect.Descriptor instead.
func (*ListRequest) Descriptor() ([]byte, []int) {
	return file_cm_server_v1_server_proto_rawDescGZIP(), []int{13}
}

func (x *ListRequest) GetPrefix() string {
	if x != nil {
		return x.Prefix
	}
	return ""
}

type ListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sessions      []*Session             `protobuf:"bytes,1,rep,name=sessions,proto3" json:"sessions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListResponse) Reset() {
	*x = ListResponse{}
	mi := &file_cm_server_v1_server_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListResponse) ProtoMessage() {}

func (x *ListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cm_server_v1_server_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListResponse.ProtoReflect.Descriptor instead.
func (*ListResponse) Descriptor() ([]byte, []int) {
	return file_cm_server_v1_server_proto_rawDescGZIP(), []int{14}
}

func (x *ListResponse) GetSessions() []*Session {
	if x != nil {
		return x.Sessions
	}
	return nil
}

type Session struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Name     string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	ShellPid int32                  `protobuf:"varint,2,opt,name=shell_pid,json=shellPid,proto3" json:"shell_pid,omitempty"`
	// Number of attached clients.
	Clients uint32 `protobuf:"varint,3,opt,name=clients,proto3" json:"clients,omitempty"`
	// Working directory, as reported by the shell via OSC 7. May be empty if the shell
	// does not report it.
	Cwd string `protobuf:"bytes,4,opt,name=cwd,proto3" json:"cwd,omitempty"`
	// Whether cwd is on this host. A session that has ssh'd elsewhere reports a path that
	// does not exist locally, so acting on it, such as opening a new window there, is
	// wrong.
	CwdIsLocal    bool   `protobuf:"varint,5,opt,name=cwd_is_local,json=cwdIsLocal,proto3" json:"cwd_is_local,omitempty"`
	Title         string `protobuf:"bytes,6,opt,name=title,proto3" json:"title,omitempty"`
	CreatedAtUnix int64  `protobuf:"varint,7,opt,name=created_at_unix,json=createdAtUnix,proto3" json:"created_at_unix,omitempty"`
	Exited        bool   `protobuf:"varint,8,opt,name=exited,proto3" json:"exited,omitempty"`
	ExitCode      int32  `protobuf:"varint,9,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	// Lifecycle stage. Preferred over exited, which cannot distinguish a shell that exited from a
	// shim that vanished; exited remains for compatibility.
	State SessionState `protobuf:"varint,10,opt,name=state,proto3,enum=cm.server.v1.SessionState" json:"state,omitempty"`
	// Working directory as the shell reported it, which is a URI for OSC 7 and keeps the host, so a
	// caller can tell a remote directory from a local one. cwd holds the decoded local path.
	CwdUri        string `protobuf:"bytes,11,opt,name=cwd_uri,json=cwdUri,proto3" json:"cwd_uri,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Session) Reset() {
	*x = Session{}
	mi := &file_cm_server_v1_server_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Session) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Session) ProtoMessage() {}

func (x *Session) ProtoReflect() protoreflect.Message {
	mi := &file_cm_server_v1_server_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Session.ProtoReflect.Descriptor instead.
func (*Session) Descriptor() ([]byte, []int) {
	return file_cm_server_v1_server_proto_rawDescGZIP(), []int{15}
}

func (x *Session) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Session) GetShellPid() int32 {
	if x != nil {
		return x.ShellPid
	}
	return 0
}

func (x *Session) GetClients() uint32 {
	if x != nil {
		return x.Clients
	}
	return 0
}

func (x *Session) GetCwd() string {
	if x != nil {
		return x.Cwd
	}
	return ""
}

func (x *Session) GetCwdIsLocal() bool {
	if x != nil {
		return x.CwdIsLocal
	}
	return false
}

func (x *Session) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Session) GetCreatedAtUnix() int64 {
	if x != nil {
		return x.CreatedAtUnix
	}
	return 0
}

func (x *Session) GetExited() bool {
	if x != nil {
		return x.Exited
	}
	return false
}

func (x *Session) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

func (x *Session) GetState() SessionState {
	if x != nil {
		return x.State
	}
	return SessionState_SESSION_STATE_UNSPECIFIED
}

func (x *Session) GetCwdUri() string {
	if x != nil {
		return x.CwdUri
	}
	return ""
}

type KillRequest struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Sessions []string               `protobuf:"bytes,1,rep,name=sessions,proto3" json:"sessions,omitempty"`
	// Remove the session record even if its shim cannot be reached. Without this, an
	// unreachable shim is left alone: it may be busy rather than dead, and discarding the
	// record would orphan it permanently.
	Force         bool `protobuf:"varint,2,opt,name=force,proto3" json:"force,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KillRequest) Reset() {
	*x = KillRequest{}
	mi := &file_cm_server_v1_server_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KillRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KillRequest) ProtoMessage() {}

func (x *KillRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cm_server_v1_server_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KillRequest.ProtoReflect.Descriptor instead.
func (*KillRequest) Descriptor() ([]byte, []int) {
	return file_cm_server_v1_server_proto_rawDescGZIP(), []int{16}
}

func (x *KillRequest) GetSessions() []string {
	if x != nil {
		return x.Sessions
	}
	return nil
}

func (x *KillRequest) GetForce() bool {
	if x != nil {
		return x.Force
	}
	return false
}

type KillResponse struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Killed []string               `protobuf:"bytes,1,rep,name=killed,proto3" json:"killed,omitempty"`
	// Sessions that could not be killed, keyed by name.
	Errors        map[string]string `protobuf:"bytes,2,rep,name=errors,proto3" json:"errors,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KillResponse) Reset() {
	*x = KillResponse{}
	mi := &file_cm_server_v1_server_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KillResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KillResponse) ProtoMessage() {}

func (x *KillResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cm_server_v1_server_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KillResponse.ProtoReflect.Descriptor instead.
func (*KillResponse) Descriptor() ([]byte, []int) {
	return file_cm_server_v1_server_proto_rawDescGZIP(), []int{17}
}

func (x *KillResponse) GetKilled() []string {
	if x != nil {
		return x.Killed
	}
	return nil
}

func (x *KillResponse) GetErrors() map[string]string {
	if x != nil {
		return x.Errors
	}
	return nil
}

type SendRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Session       string                 `protobuf:"bytes,1,opt,name=session,proto3" json:"session,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendRequest) Reset() {
	*x = SendRequest{}
	mi := &file_cm_server_v1_server_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendRequest) ProtoMessage() {}

func (x *SendRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cm_server_v1_server_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendRequest.ProtoReflect.Descriptor instead.
func (*SendRequest) Descriptor() ([]byte, []int) {
	return file_cm_server_v1_server_proto_rawDescGZIP(), []int{18}
}

func (x *SendRequest) GetSession() string {
	if x != nil {
		return x.Session
	}
	return ""
}

func (x *SendRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type SendResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendResponse) Reset() {
	*x = SendResponse{}
	mi := &file_cm_server_v1_server_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendResponse) ProtoMessage() {}

func (x *SendResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cm_server_v1_server_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendResponse.ProtoReflect.Descriptor instead.
func (*SendResponse) Descriptor() ([]byte, []int) {
	return file_cm_server_v1_server_proto_rawDescGZIP(), []int{19}
}

type HistoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Session       string                 `protobuf:"bytes,1,opt,name=session,proto3" json:"session,omitempty"`
	Format        HistoryFormat          `protobuf:"varint,2,opt,name=format,proto3,enum=cm.server.v1.HistoryFormat" json:"format,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HistoryRequest) Reset() {
	*x = HistoryRequest{}
	mi := &file_cm_server_v1_server_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HistoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HistoryRequest) ProtoMessage() {}

func (x *HistoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cm_server_v1_server_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HistoryRequest.ProtoReflect.Descriptor instead.
func (*HistoryRequest) Descriptor() ([]byte, []int) {
	return file_cm_server_v1_server_proto_rawDescGZIP(), []int{20}
}

func (x *HistoryRequest) GetSession() string {
	if x != nil {
		return x.Session
	}
	return ""
}

func (x *HistoryRequest) GetFormat() HistoryFormat {
	if x != nil {
		return x.Format
	}
	return HistoryFormat_HISTORY_FORMAT_UNSPECIFIED
}

type HistoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HistoryResponse) Reset() {
	*x = HistoryResponse{}
	mi := &file_cm_server_v1_server_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HistoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HistoryResponse) ProtoMessage() {}

func (x *HistoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cm_server_v1_server_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HistoryResponse.ProtoReflect.Descriptor instead.
func (*HistoryResponse) Descriptor() ([]byte, []int) {
	return file_cm_server_v1_server_proto_rawDescGZIP(), []int{21}
}

func (x *HistoryResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type GetEnvRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Session       string                 `protobuf:"bytes,1,opt,name=session,proto3" json:"session,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEnvRequest) Reset() {
	*x = GetEnvRequest{}
	mi := &file_cm_server_v1_server_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEnvRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEnvRequest) ProtoMessage() {}

func (x *GetEnvRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cm_server_v1_server_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEnvRequest.ProtoReflect.Descriptor instead.
func (*GetEnvRequest) Descriptor() ([]byte, []int) {
	return file_cm_server_v1_server_proto_rawDescGZIP(), []int{22}
}

func (x *GetEnvRequest) GetSession() string {
	if x != nil {
		return x.Session
	}
	return ""
}

type GetEnvResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Variables the latest client reported, as KEY -> VALUE.
	Env           map[string]string `protobuf:"bytes,1,rep,name=env,proto3" json:"env,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEnvResponse) Reset() {
	*x = GetEnvResponse{}
	mi := &file_cm_server_v1_server_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEnvResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEnvResponse) ProtoMessage() {}

func (x *GetEnvResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cm_server_v1_server_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEnvResponse.ProtoReflect.Descriptor instead.
func (*GetEnvResponse) Descriptor() ([]byte, []int) {
	return file_cm_server_v1_server_proto_rawDescGZIP(), []int{23}
}

func (x *GetEnvResponse) GetEnv() map[string]string {
	if x != nil {
		return x.Env
	}
	return nil
}

var File_cm_server_v1_server_proto protoreflect.FileDescriptor

const file_cm_server_v1_server_proto_rawDesc = "" +
	"\n" +
	"\x19cm/server/v1/server.proto\x12\fcm.server.v1\"\x11\n" +
	"\x0fShutdownRequest\"\x12\n" +
	"\x10ShutdownResponse\"\xcf\x01\n" +
	"\rAttachRequest\x12(\n" +
	"\x04open\x18\x01 \x01(\v2\x12.cm.server.v1.OpenH\x00R\x04open\x12+\n" +
	"\x05input\x18\x02 \x01(\v2\x13.cm.server.v1.InputH\x00R\x05input\x12.\n" +
	"\x06resize\x18\x03 \x01(\v2\x14.cm.server.v1.ResizeH\x00R\x06resize\x12.\n" +
	"\x06detach\x18\x04 \x01(\v2\x14.cm.server.v1.DetachH\x00R\x06detachB\a\n" +
	"\x05event\"\x88\x04\n" +
	"\x04Open\x12\x18\n" +
	"\asession\x18\x01 \x01(\tR\asession\x12\x12\n" +
	"\x04rows\x18\x02 \x01(\rR\x04rows\x12\x12\n" +
	"\x04cols\x18\x03 \x01(\rR\x04cols\x12\x17\n" +
	"\ax_pixel\x18\x04 \x01(\rR\x06xPixel\x12\x17\n" +
	"\ay_pixel\x18\x05 \x01(\rR\x06yPixel\x12+\n" +
	"\x0fresume_from_seq\x18\x06 \x01(\x04H\x00R\rresumeFromSeq\x88\x01\x01\x12\x10\n" +
	"\x03own\x18\a \x01(\bR\x03own\x12\x1b\n" +
	"\tread_only\x18\b \x01(\bR\breadOnly\x12\x18\n" +
	"\acommand\x18\t \x03(\tR\acommand\x12\x10\n" +
	"\x03cwd\x18\n" +
	" \x01(\tR\x03cwd\x12\x10\n" +
	"\x03env\x18\v \x03(\tR\x03env\x12@\n" +
	"\n" +
	"client_env\x18\f \x03(\v2!.cm.server.v1.Open.ClientEnvEntryR\tclientEnv\x12\x18\n" +
	"\apersist\x18\r \x01(\bR\apersist\x12\x1d\n" +
	"\n" +
	"on_restore\x18\x0e \x01(\tR\tonRestore\x12%\n" +
	"\x0ecapture_output\x18\x0f \x01(\bR\rcaptureOutput\x1a<\n" +
	"\x0eClientEnvEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\x12\n" +
	"\x10_resume_from_seq\"\x1b\n" +
	"\x05Input\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\"b\n" +
	"\x06Resize\x12\x12\n" +
	"\x04rows\x18\x01 \x01(\rR\x04rows\x12\x12\n" +
	"\x04cols\x18\x02 \x01(\rR\x04cols\x12\x17\n" +
	"\ax_pixel\x18\x03 \x01(\rR\x06xPixel\x12\x17\n" +
	"\ay_pixel\x18\x04 \x01(\rR\x06yPixel\"\b\n" +
	"\x06Detach\"\x95\x02\n" +
	"\x0eAttachResponse\x12.\n" +
	"\x06opened\x18\x01 \x01(\v2\x14.cm.server.v1.OpenedH\x00R\x06opened\x12.\n" +
	"\x06output\x18\x02 \x01(\v2\x14.cm.server.v1.OutputH\x00R\x06output\x12.\n" +
	"\x06exited\x18\x03 \x01(\v2\x14.cm.server.v1.ExitedH\x00R\x06exited\x124\n" +
	"\bmetadata\x18\x04 \x01(\v2\x16.cm.server.v1.MetadataH\x00R\bmetadata\x124\n" +
	"\bdetached\x18\x05 \x01(\v2\x16.cm.server.v1.DetachedH\x00R\bdetachedB\a\n" +
	"\x05event\"\n" +
	"\n" +
	"\bDetached\"T\n" +
	"\bMetadata\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12\x10\n" +
	"\x03cwd\x18\x02 \x01(\tR\x03cwd\x12 \n" +
	"\fcwd_is_local\x18\x03 \x01(\bR\n" +
	"cwdIsLocal\"q\n" +
	"\x06Opened\x12\x18\n" +
	"\asession\x18\x01 \x01(\tR\asession\x12\x18\n" +
	"\acreated\x18\x02 \x01(\bR\acreated\x12\x18\n" +
	"\arestore\x18\x03 \x01(\fR\arestore\x12\x19\n" +
	"\bnext_seq\x18\x04 \x01(\x04R\anextSeq\"@\n" +
	"\x06Output\x12\x10\n" +
	"\x03seq\x18\x01 \x01(\x04R\x03seq\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\x12\x10\n" +
	"\x03gap\x18\x03 \x01(\bR\x03gap\"%\n" +
	"\x06Exited\x12\x1b\n" +
	"\texit_code\x18\x01 \x01(\x05R\bexitCode\"%\n" +
	"\vListRequest\x12\x16\n" +
	"\x06prefix\x18\x01 \x01(\tR\x06prefix\"A\n" +
	"\fListResponse\x121\n" +
	"\bsessions\x18\x01 \x03(\v2\x15.cm.server.v1.SessionR\bsessions\"\xc6\x02\n" +
	"\aSession\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1b\n" +
	"\tshell_pid\x18\x02 \x01(\x05R\bshellPid\x12\x18\n" +
	"\aclients\x18\x03 \x01(\rR\aclients\x12\x10\n" +
	"\x03cwd\x18\x04 \x01(\tR\x03cwd\x12 \n" +
	"\fcwd_is_local\x18\x05 \x01(\bR\n" +
	"cwdIsLocal\x12\x14\n" +
	"\x05title\x18\x06 \x01(\tR\x05title\x12&\n" +
	"\x0fcreated_at_unix\x18\a \x01(\x03R\rcreatedAtUnix\x12\x16\n" +
	"\x06exited\x18\b \x01(\bR\x06exited\x12\x1b\n" +
	"\texit_code\x18\t \x01(\x05R\bexitCode\x120\n" +
	"\x05state\x18\n" +
	" \x01(\x0e2\x1a.cm.server.v1.SessionStateR\x05state\x12\x17\n" +
	"\acwd_uri\x18\v \x01(\tR\x06cwdUri\"?\n" +
	"\vKillRequest\x12\x1a\n" +
	"\bsessions\x18\x01 \x03(\tR\bsessions\x12\x14\n" +
	"\x05force\x18\x02 \x01(\bR\x05force\"\xa1\x01\n" +
	"\fKillResponse\x12\x16\n" +
	"\x06killed\x18\x01 \x03(\tR\x06killed\x12>\n" +
	"\x06errors\x18\x02 \x03(\v2&.cm.server.v1.KillResponse.ErrorsEntryR\x06errors\x1a9\n" +
	"\vErrorsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\";\n" +
	"\vSendRequest\x12\x18\n" +
	"\asession\x18\x01 \x01(\tR\asession\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\"\x0e\n" +
	"\fSendResponse\"_\n" +
	"\x0eHistoryRequest\x12\x18\n" +
	"\asession\x18\x01 \x01(\tR\asession\x123\n" +
	"\x06format\x18\x02 \x01(\x0e2\x1b.cm.server.v1.HistoryFormatR\x06format\"%\n" +
	"\x0fHistoryResponse\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\")\n" +
	"\rGetEnvRequest\x12\x18\n" +
	"\asession\x18\x01 \x01(\tR\asession\"\x81\x01\n" +
	"\x0eGetEnvResponse\x127\n" +
	"\x03env\x18\x01 \x03(\v2%.cm.server.v1.GetEnvResponse.EnvEntryR\x03env\x1a6\n" +
	"\bEnvEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01*z\n" +
	"\fSessionState\x12\x1d\n" +
	"\x19SESSION_STATE_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15SESSION_STATE_RUNNING\x10\x01\x12\x18\n" +
	"\x14SESSION_STATE_EXITED\x10\x02\x12\x16\n" +
	"\x12SESSION_STATE_DEAD\x10\x03*_\n" +
	"\rHistoryFormat\x12\x1e\n" +
	"\x1aHISTORY_FORMAT_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11HISTORY_FORMAT_VT\x10\x01\x12\x17\n" +
	"\x13HISTORY_FORMAT_HTML\x10\x022\xe6\x03\n" +
	"\x06Server\x12G\n" +
	"\x06Attach\x12\x1b.cm.server.v1.AttachRequest\x1a\x1c.cm.server.v1.AttachResponse(\x010\x01\x12=\n" +
	"\x04List\x12\x19.cm.server.v1.ListRequest\x1a\x1a.cm.server.v1.ListResponse\x12=\n" +
	"\x04Kill\x12\x19.cm.server.v1.KillRequest\x1a\x1a.cm.server.v1.KillResponse\x12=\n" +
	"\x04Send\x12\x19.cm.server.v1.SendRequest\x1a\x1a.cm.server.v1.SendResponse\x12F\n" +
	"\aHistory\x12\x1c.cm.server.v1.HistoryRequest\x1a\x1d.cm.server.v1.HistoryResponse\x12C\n" +
	"\x06GetEnv\x12\x1b.cm.server.v1.GetEnvRequest\x1a\x1c.cm.server.v1.GetEnvResponse\x12I\n" +
	"\bShutdown\x12\x1d.cm.server.v1.ShutdownRequest\x1a\x1e.cm.server.v1.ShutdownResponseB3Z1github.com/chancez/cm/proto/cm/server/v1;serverv1b\x06proto3"

var (
	file_cm_server_v1_server_proto_rawDescOnce sync.Once
	file_cm_server_v1_server_proto_rawDescData []byte
)

func file_cm_server_v1_server_proto_rawDescGZIP() []byte {
	file_cm_server_v1_server_proto_rawDescOnce.Do(func() {
		file_cm_server_v1_server_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_cm_server_v1_server_proto_rawDesc), len(file_cm_server_v1_server_proto_rawDesc)))
	})
	return file_cm_server_v1_server_proto_rawDescData
}

var file_cm_server_v1_server_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_cm_server_v1_server_proto_msgTypes = make([]protoimpl.MessageInfo, 27)
var file_cm_server_v1_server_proto_goTypes = []any{
	(SessionState)(0),        // 0: cm.server.v1.SessionState
	(HistoryFormat)(0),       // 1: cm.server.v1.HistoryFormat
	(*ShutdownRequest)(nil),  // 2: cm.server.v1.ShutdownRequest
	(*ShutdownResponse)(nil), // 3: cm.server.v1.ShutdownResponse
	(*AttachRequest)(nil),    // 4: cm.server.v1.AttachRequest
	(*Open)(nil),             // 5: cm.server.v1.Open
	(*Input)(nil),            // 6: cm.server.v1.Input
	(*Resize)(nil),           // 7: cm.server.v1.Resize
	(*Detach)(nil),           // 8: cm.server.v1.Detach
	(*AttachResponse)(nil),   // 9: cm.server.v1.AttachResponse
	(*Detached)(nil),         // 10: cm.server.v1.Detached
	(*Metadata)(nil),         // 11: cm.server.v1.Metadata
	(*Opened)(nil),           // 12: cm.server.v1.Opened
	(*Output)(nil),           // 13: cm.server.v1.Output
	(*Exited)(nil),           // 14: cm.server.v1.Exited
	(*ListRequest)(nil),      // 15: cm.server.v1.ListRequest
	(*ListResponse)(nil),     // 16: cm.server.v1.ListResponse
	(*Session)(nil),          // 17: cm.server.v1.Session
	(*KillRequest)(nil),      // 18: cm.server.v1.KillRequest
	(*KillResponse)(nil),     // 19: cm.server.v1.KillResponse
	(*SendRequest)(nil),      // 20: cm.server.v1.SendRequest
	(*SendResponse)(nil),     // 21: cm.server.v1.SendResponse
	(*HistoryRequest)(nil),   // 22: cm.server.v1.HistoryRequest
	(*HistoryResponse)(nil),  // 23: cm.server.v1.HistoryResponse
	(*GetEnvRequest)(nil),    // 24: cm.server.v1.GetEnvRequest
	(*GetEnvResponse)(nil),   // 25: cm.server.v1.GetEnvResponse
	nil,                      // 26: cm.server.v1.Open.ClientEnvEntry
	nil,                      // 27: cm.server.v1.KillResponse.ErrorsEntry
	nil,                      // 28: cm.server.v1.GetEnvResponse.EnvEntry
}
var file_cm_server_v1_server_proto_depIdxs = []int32{
	5,  // 0: cm.server.v1.AttachRequest.open:type_name -> cm.server.v1.Open
	6,  // 1: cm.server.v1.AttachRequest.input:type_name -> cm.server.v1.Input
	7,  // 2: cm.server.v1.AttachRequest.resize:type_name -> cm.server.v1.Resize
	8,  // 3: cm.server.v1.AttachRequest.detach:type_name -> cm.server.v1.Detach
	26, // 4: cm.server.v1.Open.client_env:type_name -> cm.server.v1.Open.ClientEnvEntry
	12, // 5: cm.server.v1.AttachResponse.opened:type_name -> cm.server.v1.Opened
	13, // 6: cm.server.v1.AttachResponse.output:type_name -> cm.server.v1.Output
	14, // 7: cm.server.v1.AttachResponse.exited:type_name -> cm.server.v1.Exited
	11, // 8: cm.server.v1.AttachResponse.metadata:type_name -> cm.server.v1.Metadata
	10, // 9: cm.server.v1.AttachResponse.detached:type_name -> cm.server.v1.Detached
	17, // 10: cm.server.v1.ListResponse.sessions:type_name -> cm.server.v1.Session
	0,  // 11: cm.server.v1.Session.state:type_name -> cm.server.v1.SessionState
	27, // 12: cm.server.v1.KillResponse.errors:type_name -> cm.server.v1.KillResponse.ErrorsEntry
	1,  // 13: cm.server.v1.HistoryRequest.format:type_name -> cm.server.v1.HistoryFormat
	28, // 14: cm.server.v1.GetEnvResponse.env:type_name -> cm.server.v1.GetEnvResponse.EnvEntry
	4,  // 15: cm.server.v1.Server.Attach:input_type -> cm.server.v1.AttachRequest
	15, // 16: cm.server.v1.Server.List:input_type -> cm.server.v1.ListRequest
	18, // 17: cm.server.v1.Server.Kill:input_type -> cm.server.v1.KillRequest
	20, // 18: cm.server.v1.Server.Send:input_type -> cm.server.v1.SendRequest
	22, // 19: cm.server.v1.Server.History:input_type -> cm.server.v1.HistoryRequest
	24, // 20: cm.server.v1.Server.GetEnv:input_type -> cm.server.v1.GetEnvRequest
	2,  // 21: cm.server.v1.Server.Shutdown:input_type -> cm.server.v1.ShutdownRequest
	9,  // 22: cm.server.v1.Server.Attach:output_type -> cm.server.v1.AttachResponse
	16, // 23: cm.server.v1.Server.List:output_type -> cm.server.v1.ListResponse
	19, // 24: cm.server.v1.Server.Kill:output_type -> cm.server.v1.KillResponse
	21, // 25: cm.server.v1.Server.Send:output_type -> cm.server.v1.SendResponse
	23, // 26: cm.server.v1.Server.History:output_type -> cm.server.v1.HistoryResponse
	25, // 27: cm.server.v1.Server.GetEnv:output_type -> cm.server.v1.GetEnvResponse
	3,  // 28: cm.server.v1.Server.Shutdown:output_type -> cm.server.v1.ShutdownResponse
	22, // [22:29] is the sub-list for method output_type
	15, // [15:22] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_cm_server_v1_server_proto_init() }
func file_cm_server_v1_server_proto_init() {
	if File_cm_server_v1_server_proto != nil {
		return
	}
	file_cm_server_v1_server_proto_msgTypes[2].OneofWrappers = []any{
		(*AttachRequest_Open)(nil),
		(*AttachRequest_Input)(nil),
		(*AttachRequest_Resize)(nil),
		(*AttachRequest_Detach)(nil),
	}
	file_cm_server_v1_server_proto_msgTypes[3].OneofWrappers = []any{}
	file_cm_server_v1_server_proto_msgTypes[7].OneofWrappers = []any{
		(*AttachResponse_Opened)(nil),
		(*AttachResponse_Output)(nil),
		(*AttachResponse_Exited)(nil),
		(*AttachResponse_Metadata)(nil),
		(*AttachResponse_Detached)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cm_server_v1_server_proto_rawDesc), len(file_cm_server_v1_server_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   27,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_cm_server_v1_server_proto_goTypes,
		DependencyIndexes: file_cm_server_v1_server_proto_depIdxs,
		EnumInfos:         file_cm_server_v1_server_proto_enumTypes,
		MessageInfos:      file_cm_server_v1_server_proto_msgTypes,
	}.Build()
	File_cm_server_v1_server_proto = out.File
	file_cm_server_v1_server_proto_goTypes = nil
	file_cm_server_v1_server_proto_depIdxs = nil
}
