// Code generated by protoc-gen-go-ttrpc. DO NOT EDIT.
// source: cm/server/v1/server.proto
package serverv1

import (
	context "context"
	ttrpc "github.com/containerd/ttrpc"
)

type ServerService interface {
	Attach(context.Context, Server_AttachServer) error
	List(context.Context, *ListRequest) (*ListResponse, error)
	Kill(context.Context, *KillRequest) (*KillResponse, error)
	Send(context.Context, *SendRequest) (*SendResponse, error)
}

type Server_AttachServer interface {
	Send(*AttachResponse) error
	Recv() (*AttachRequest, error)
	ttrpc.StreamServer
}

type serverAttachServer struct {
	ttrpc.StreamServer
}

func (x *serverAttachServer) Send(m *AttachResponse) error {
	return x.StreamServer.SendMsg(m)
}

func (x *serverAttachServer) Recv() (*AttachRequest, error) {
	m := new(AttachRequest)
	if err := x.StreamServer.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func RegisterServerService(srv *ttrpc.Server, svc ServerService) {
	srv.RegisterService("cm.server.v1.Server", &ttrpc.ServiceDesc{
		Methods: map[string]ttrpc.Method{
			"List": func(ctx context.Context, unmarshal func(interface{}) error) (interface{}, error) {
				var req ListRequest
				if err := unmarshal(&req); err != nil {
					return nil, err
				}
				return svc.List(ctx, &req)
			},
			"Kill": func(ctx context.Context, unmarshal func(interface{}) error) (interface{}, error) {
				var req KillRequest
				if err := unmarshal(&req); err != nil {
					return nil, err
				}
				return svc.Kill(ctx, &req)
			},
			"Send": func(ctx context.Context, unmarshal func(interface{}) error) (interface{}, error) {
				var req SendRequest
				if err := unmarshal(&req); err != nil {
					return nil, err
				}
				return svc.Send(ctx, &req)
			},
		},
		Streams: map[string]ttrpc.Stream{
			"Attach": {
				Handler: func(ctx context.Context, stream ttrpc.StreamServer) (interface{}, error) {
					return nil, svc.Attach(ctx, &serverAttachServer{stream})
				},
				StreamingClient: true,
				StreamingServer: true,
			},
		},
	})
}

type ServerClient interface {
	Attach(context.Context) (Server_AttachClient, error)
	List(context.Context, *ListRequest) (*ListResponse, error)
	Kill(context.Context, *KillRequest) (*KillResponse, error)
	Send(context.Context, *SendRequest) (*SendResponse, error)
}

type serverClient struct {
	client *ttrpc.Client
}

func NewServerClient(client *ttrpc.Client) ServerClient {
	return &serverClient{
		client: client,
	}
}

func (c *serverClient) Attach(ctx context.Context) (Server_AttachClient, error) {
	stream, err := c.client.NewStream(ctx, &ttrpc.StreamDesc{
		StreamingClient: true,
		StreamingServer: true,
	}, "cm.server.v1.Server", "Attach", nil)
	if err != nil {
		return nil, err
	}
	x := &serverAttachClient{stream}
	return x, nil
}

type Server_AttachClient interface {
	Send(*AttachRequest) error
	Recv() (*AttachResponse, error)
	ttrpc.ClientStream
}

type serverAttachClient struct {
	ttrpc.ClientStream
}

func (x *serverAttachClient) Send(m *AttachRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *serverAttachClient) Recv() (*AttachResponse, error) {
	m := new(AttachResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *serverClient) List(ctx context.Context, req *ListRequest) (*ListResponse, error) {
	var resp ListResponse
	if err := c.client.Call(ctx, "cm.server.v1.Server", "List", req, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}

func (c *serverClient) Kill(ctx context.Context, req *KillRequest) (*KillResponse, error) {
	var resp KillResponse
	if err := c.client.Call(ctx, "cm.server.v1.Server", "Kill", req, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}

func (c *serverClient) Send(ctx context.Context, req *SendRequest) (*SendResponse, error) {
	var resp SendResponse
	if err := c.client.Call(ctx, "cm.server.v1.Server", "Send", req, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}
