// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: cm/server/v1/server.proto

// Package cm.server.v1 is the interface clients use. The server is the only entry point:
// clients never talk to a shim directly.
//
// Unlike the shim API, this surface may evolve. A client and server are upgraded
// together, and a client that meets an incompatible server can simply refuse to attach
// with a clear message.

package serverv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ShutdownRequest asks the server to stop.
// ReportedState is what a program in a session says about itself.
//
// Overlaps deliberately with what cm derives from OSC 133, and takes precedence over it: a program that
// says what it is doing knows better than a shell marker does. A coding agent is the case that needs
// this, since its shell reports one long-running command while the agent moves between working, waiting
// for input, and done.
type ReportedState int32

const (
	ReportedState_REPORTED_STATE_UNSPECIFIED ReportedState = 0
	// IDLE means the program finished and is not waiting on anything.
	ReportedState_REPORTED_STATE_IDLE ReportedState = 1
	// BUSY means it is working.
	ReportedState_REPORTED_STATE_BUSY ReportedState = 2
	// BLOCKED means it needs input and will not progress until it gets some.
	//
	// The state OSC 133 cannot express: a shell reports a command as running whether it is computing or
	// sitting at a prompt of its own, so only the program itself can say which.
	ReportedState_REPORTED_STATE_BLOCKED ReportedState = 3
	// CLEAR removes a report, so the session falls back to what cm derives from the shell.
	ReportedState_REPORTED_STATE_CLEAR ReportedState = 4
)

// Enum value maps for ReportedState.
var (
	ReportedState_name = map[int32]string{
		0: "REPORTED_STATE_UNSPECIFIED",
		1: "REPORTED_STATE_IDLE",
		2: "REPORTED_STATE_BUSY",
		3: "REPORTED_STATE_BLOCKED",
		4: "REPORTED_STATE_CLEAR",
	}
	ReportedState_value = map[string]int32{
		"REPORTED_STATE_UNSPECIFIED": 0,
		"REPORTED_STATE_IDLE":        1,
		"REPORTED_STATE_BUSY":        2,
		"REPORTED_STATE_BLOCKED":     3,
		"REPORTED_STATE_CLEAR":       4,
	}
)

func (x ReportedState) Enum() *ReportedState {
	p := new(ReportedState)
	*p = x
	return p
}

func (x ReportedState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ReportedState) Descriptor() protoreflect.EnumDescriptor {
	return file_cm_server_v1_server_proto_enumTypes[0].Descriptor()
}

func (ReportedState) Type() protoreflect.EnumType {
	return &file_cm_server_v1_server_proto_enumTypes[0]
}

func (x ReportedState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ReportedState.Descriptor instead.
func (ReportedState) EnumDescriptor() ([]byte, []int) {
	return file_cm_server_v1_server_proto_rawDescGZIP(), []int{0}
}

// WaitState is a condition a caller can wait for.
type WaitState int32

const (
	WaitState_WAIT_STATE_UNSPECIFIED WaitState = 0
	// IDLE means the shell is at a prompt with no command running, from OSC 133.
	WaitState_WAIT_STATE_IDLE WaitState = 1
	// BUSY means a command is running.
	WaitState_WAIT_STATE_BUSY WaitState = 2
	// EXITED means the session ended, whatever its status.
	WaitState_WAIT_STATE_EXITED WaitState = 3
	// BLOCKED means a program in the session reported that it needs input.
	//
	// Only reachable when something reports it: a shell marks a command as running whether it is computing
	// or waiting at a prompt of its own, so this cannot be derived from OSC 133.
	WaitState_WAIT_STATE_BLOCKED WaitState = 4
)

// Enum value maps for WaitState.
var (
	WaitState_name = map[int32]string{
		0: "WAIT_STATE_UNSPECIFIED",
		1: "WAIT_STATE_IDLE",
		2: "WAIT_STATE_BUSY",
		3: "WAIT_STATE_EXITED",
		4: "WAIT_STATE_BLOCKED",
	}
	WaitState_value = map[string]int32{
		"WAIT_STATE_UNSPECIFIED": 0,
		"WAIT_STATE_IDLE":        1,
		"WAIT_STATE_BUSY":        2,
		"WAIT_STATE_EXITED":      3,
		"WAIT_STATE_BLOCKED":     4,
	}
)

func (x WaitState) Enum() *WaitState {
	p := new(WaitState)
	*p = x
	return p
}

func (x WaitState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WaitState) Descriptor() protoreflect.EnumDescriptor {
	return file_cm_server_v1_server_proto_enumTypes[1].Descriptor()
}

func (WaitState) Type() protoreflect.EnumType {
	return &file_cm_server_v1_server_proto_enumTypes[1]
}

func (x WaitState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WaitState.Descriptor instead.
func (WaitState) EnumDescriptor() ([]byte, []int) {
	return file_cm_server_v1_server_proto_rawDescGZIP(), []int{1}
}

// SessionState is a session's lifecycle stage.
type SessionState int32

const (
	SessionState_SESSION_STATE_UNSPECIFIED SessionState = 0
	// The session has a live shim holding a running shell.
	SessionState_SESSION_STATE_RUNNING SessionState = 1
	// The shell exited, and exit_code says with what.
	SessionState_SESSION_STATE_EXITED SessionState = 2
	// The shim could not be reached. Distinct from exited because the outcome is unknown rather
	// than observed, so exit_code means nothing.
	SessionState_SESSION_STATE_DEAD SessionState = 3
)

// Enum value maps for SessionState.
var (
	SessionState_name = map[int32]string{
		0: "SESSION_STATE_UNSPECIFIED",
		1: "SESSION_STATE_RUNNING",
		2: "SESSION_STATE_EXITED",
		3: "SESSION_STATE_DEAD",
	}
	SessionState_value = map[string]int32{
		"SESSION_STATE_UNSPECIFIED": 0,
		"SESSION_STATE_RUNNING":     1,
		"SESSION_STATE_EXITED":      2,
		"SESSION_STATE_DEAD":        3,
	}
)

func (x SessionState) Enum() *SessionState {
	p := new(SessionState)
	*p = x
	return p
}

func (x SessionState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SessionState) Descriptor() protoreflect.EnumDescriptor {
	return file_cm_server_v1_server_proto_enumTypes[2].Descriptor()
}

func (SessionState) Type() protoreflect.EnumType {
	return &file_cm_server_v1_server_proto_enumTypes[2]
}

func (x SessionState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SessionState.Descriptor instead.
func (SessionState) EnumDescriptor() ([]byte, []int) {
	return file_cm_server_v1_server_proto_rawDescGZIP(), []int{2}
}

// HistoryFormat selects how session contents are rendered.
type HistoryFormat int32

const (
	// Plain text, suitable for piping to a file or a pager.
	HistoryFormat_HISTORY_FORMAT_UNSPECIFIED HistoryFormat = 0
	// Escape sequences, preserving colors and styling.
	HistoryFormat_HISTORY_FORMAT_VT HistoryFormat = 1
	// HTML, preserving styling.
	HistoryFormat_HISTORY_FORMAT_HTML HistoryFormat = 2
)

// Enum value maps for HistoryFormat.
var (
	HistoryFormat_name = map[int32]string{
		0: "HISTORY_FORMAT_UNSPECIFIED",
		1: "HISTORY_FORMAT_VT",
		2: "HISTORY_FORMAT_HTML",
	}
	HistoryFormat_value = map[string]int32{
		"HISTORY_FORMAT_UNSPECIFIED": 0,
		"HISTORY_FORMAT_VT":          1,
		"HISTORY_FORMAT_HTML":        2,
	}
)

func (x HistoryFormat) Enum() *HistoryFormat {
	p := new(HistoryFormat)
	*p = x
	return p
}

func (x HistoryFormat) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (HistoryFormat) Descriptor() protoreflect.EnumDescriptor {
	return file_cm_server_v1_server_proto_enumTypes[3].Descriptor()
}

func (HistoryFormat) Type() protoreflect.EnumType {
	return &file_cm_server_v1_server_proto_enumTypes[3]
}

func (x HistoryFormat) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use HistoryFormat.Descriptor instead.
func (HistoryFormat) EnumDescriptor() ([]byte, []int) {
	return file_cm_server_v1_server_proto_rawDescGZIP(), []int{3}
}

type StatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusRequest) Reset() {
	*x = StatusRequest{}
	mi := &file_cm_server_v1_server_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusRequest) ProtoMessage() {}

func (x *StatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cm_server_v1_server_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusRequest.ProtoReflect.Descriptor instead.
func (*StatusRequest) Descriptor() ([]byte, []int) {
	return file_cm_server_v1_server_proto_rawDescGZIP(), []int{0}
}

type StatusResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Process id of the server, so it can be found without scanning the process table.
	Pid int32 `protobuf:"varint,1,opt,name=pid,proto3" json:"pid,omitempty"`
	// When the server started, as unix seconds. Sent as a timestamp rather than a duration so the client
	// renders the uptime, which keeps the two from disagreeing as the reply travels.
	StartedAtUnix int64 `protobuf:"varint,2,opt,name=started_at_unix,json=startedAtUnix,proto3" json:"started_at_unix,omitempty"`
	// The server's own build.
	Version string `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	// Directories in use, which is the fastest way to spot a client talking to a server started with
	// different ones.
	RuntimeDir string `protobuf:"bytes,4,opt,name=runtime_dir,json=runtimeDir,proto3" json:"runtime_dir,omitempty"`
	StateDir   string `protobuf:"bytes,5,opt,name=state_dir,json=stateDir,proto3" json:"state_dir,omitempty"`
	// Session counts by state. Separate fields rather than a map so the shape is fixed and a client does
	// not have to know which keys to expect.
	SessionsRunning int32 `protobuf:"varint,6,opt,name=sessions_running,json=sessionsRunning,proto3" json:"sessions_running,omitempty"`
	SessionsExited  int32 `protobuf:"varint,7,opt,name=sessions_exited,json=sessionsExited,proto3" json:"sessions_exited,omitempty"`
	SessionsDead    int32 `protobuf:"varint,8,opt,name=sessions_dead,json=sessionsDead,proto3" json:"sessions_dead,omitempty"`
	// Clients attached across every session, which says whether anything is watching.
	Clients int32 `protobuf:"varint,9,opt,name=clients,proto3" json:"clients,omitempty"`
	// Whether this server has the terminal emulator. A server without it cannot restore a screen, and
	// that is a property of the server rather than of the client asking.
	Terminal      bool `protobuf:"varint,10,opt,name=terminal,proto3" json:"terminal,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusResponse) Reset() {
	*x = StatusResponse{}
	mi := &file_cm_server_v1_server_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusResponse) ProtoMessage() {}

func (x *StatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cm_server_v1_server_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusResponse.ProtoReflect.Descriptor instead.
func (*StatusResponse) Descriptor() ([]byte, []int) {
	return file_cm_server_v1_server_proto_rawDescGZIP(), []int{1}
}

func (x *StatusResponse) GetPid() int32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *StatusResponse) GetStartedAtUnix() int64 {
	if x != nil {
		return x.StartedAtUnix
	}
	return 0
}

func (x *StatusResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *StatusResponse) GetRuntimeDir() string {
	if x != nil {
		return x.RuntimeDir
	}
	return ""
}

func (x *StatusResponse) GetStateDir() string {
	if x != nil {
		return x.StateDir
	}
	return ""
}

func (x *StatusResponse) GetSessionsRunning() int32 {
	if x != nil {
		return x.SessionsRunning
	}
	return 0
}

func (x *StatusResponse) GetSessionsExited() int32 {
	if x != nil {
		return x.SessionsExited
	}
	return 0
}

func (x *StatusResponse) GetSessionsDead() int32 {
	if x != nil {
		return x.SessionsDead
	}
	return 0
}

func (x *StatusResponse) GetClients() int32 {
	if x != nil {
		return x.Clients
	}
	return 0
}

func (x *StatusResponse) GetTerminal() bool {
	if x != nil {
		return x.Terminal
	}
	return false
}

type ReportRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Empty means the session the caller is in, from CM_SESSION.
	Session string        `protobuf:"bytes,1,opt,name=session,proto3" json:"session,omitempty"`
	State   ReportedState `protobuf:"varint,2,opt,name=state,proto3,enum=cm.server.v1.ReportedState" json:"state,omitempty"`
	// A short human-readable note, shown alongside the state. Optional.
	Detail string `protobuf:"bytes,3,opt,name=detail,proto3" json:"detail,omitempty"`
	// Who is reporting, for display and so one reporter's state is distinguishable from another's.
	// Optional; free-form.
	Source        string `protobuf:"bytes,4,opt,name=source,proto3" json:"source,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportRequest) Reset() {
	*x = ReportRequest{}
	mi := &file_cm_server_v1_server_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportRequest) ProtoMessage() {}

func (x *ReportRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cm_server_v1_server_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportRequest.ProtoReflect.Descriptor instead.
func (*ReportRequest) Descriptor() ([]byte, []int) {
	return file_cm_server_v1_server_proto_rawDescGZIP(), []int{2}
}

func (x *ReportRequest) GetSession() string {
	if x != nil {
		return x.Session
	}
	return ""
}

func (x *ReportRequest) GetState() ReportedState {
	if x != nil {
		return x.State
	}
	return ReportedState_REPORTED_STATE_UNSPECIFIED
}

func (x *ReportRequest) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

func (x *ReportRequest) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

type ReportResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportResponse) Reset() {
	*x = ReportResponse{}
	mi := &file_cm_server_v1_server_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportResponse) ProtoMessage() {}

func (x *ReportResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cm_server_v1_server_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportResponse.ProtoReflect.Descriptor instead.
func (*ReportResponse) Descriptor() ([]byte, []int) {
	return file_cm_server_v1_server_proto_rawDescGZIP(), []int{3}
}

type ReadRequest struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Session string                 `protobuf:"bytes,1,opt,name=session,proto3" json:"session,omitempty"`
	// How many lines from the end. Zero means everything.
	Lines uint32 `protobuf:"varint,2,opt,name=lines,proto3" json:"lines,omitempty"`
	// Whether to rejoin soft-wrapped lines. A line the terminal broke to fit its width is one line to the
	// program that wrote it, so splitting it puts a newline inside a path or a stack frame.
	Unwrap        bool `protobuf:"varint,3,opt,name=unwrap,proto3" json:"unwrap,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadRequest) Reset() {
	*x = ReadRequest{}
	mi := &file_cm_server_v1_server_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadRequest) ProtoMessage() {}

func (x *ReadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cm_server_v1_server_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadRequest.ProtoReflect.Descriptor instead.
func (*ReadRequest) Descriptor() ([]byte, []int) {
	return file_cm_server_v1_server_proto_rawDescGZIP(), []int{4}
}

func (x *ReadRequest) GetSession() string {
	if x != nil {
		return x.Session
	}
	return ""
}

func (x *ReadRequest) GetLines() uint32 {
	if x != nil {
		return x.Lines
	}
	return 0
}

func (x *ReadRequest) GetUnwrap() bool {
	if x != nil {
		return x.Unwrap
	}
	return false
}

type ReadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadResponse) Reset() {
	*x = ReadResponse{}
	mi := &file_cm_server_v1_server_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadResponse) ProtoMessage() {}

func (x *ReadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cm_server_v1_server_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadResponse.ProtoReflect.Descriptor instead.
func (*ReadResponse) Descriptor() ([]byte, []int) {
	return file_cm_server_v1_server_proto_rawDescGZIP(), []int{5}
}

func (x *ReadResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type WaitRequest struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Session string                 `protobuf:"bytes,1,opt,name=session,proto3" json:"session,omitempty"`
	Until   WaitState              `protobuf:"varint,2,opt,name=until,proto3,enum=cm.server.v1.WaitState" json:"until,omitempty"`
	// How long to wait before giving up. Zero waits indefinitely.
	//
	// Milliseconds rather than a duration string: this crosses a wire, and an integer needs no parser on
	// either side.
	TimeoutMs     uint64 `protobuf:"varint,3,opt,name=timeout_ms,json=timeoutMs,proto3" json:"timeout_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WaitRequest) Reset() {
	*x = WaitRequest{}
	mi := &file_cm_server_v1_server_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WaitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WaitRequest) ProtoMessage() {}

func (x *WaitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cm_server_v1_server_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WaitRequest.ProtoReflect.Descriptor instead.
func (*WaitRequest) Descriptor() ([]byte, []int) {
	return file_cm_server_v1_server_proto_rawDescGZIP(), []int{6}
}

func (x *WaitRequest) GetSession() string {
	if x != nil {
		return x.Session
	}
	return ""
}

func (x *WaitRequest) GetUntil() WaitState {
	if x != nil {
		return x.Until
	}
	return WaitState_WAIT_STATE_UNSPECIFIED
}

func (x *WaitRequest) GetTimeoutMs() uint64 {
	if x != nil {
		return x.TimeoutMs
	}
	return 0
}

type WaitResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Whether the condition was reached, as opposed to the wait timing out.
	Satisfied bool `protobuf:"varint,1,opt,name=satisfied,proto3" json:"satisfied,omitempty"`
	// What a program in the session reported about itself, if anything, and the note that came with it.
	ReportedState  string `protobuf:"bytes,6,opt,name=reported_state,json=reportedState,proto3" json:"reported_state,omitempty"`
	ReportedDetail string `protobuf:"bytes,7,opt,name=reported_detail,json=reportedDetail,proto3" json:"reported_detail,omitempty"`
	// The session's state when the wait returned, so a caller that timed out learns what it was instead.
	Busy          bool         `protobuf:"varint,2,opt,name=busy,proto3" json:"busy,omitempty"`
	Command       string       `protobuf:"bytes,3,opt,name=command,proto3" json:"command,omitempty"`
	State         SessionState `protobuf:"varint,4,opt,name=state,proto3,enum=cm.server.v1.SessionState" json:"state,omitempty"`
	ExitCode      int32        `protobuf:"varint,5,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WaitResponse) Reset() {
	*x = WaitResponse{}
	mi := &file_cm_server_v1_server_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WaitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WaitResponse) ProtoMessage() {}

func (x *WaitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cm_server_v1_server_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WaitResponse.ProtoReflect.Descriptor instead.
func (*WaitResponse) Descriptor() ([]byte, []int) {
	return file_cm_server_v1_server_proto_rawDescGZIP(), []int{7}
}

func (x *WaitResponse) GetSatisfied() bool {
	if x != nil {
		return x.Satisfied
	}
	return false
}

func (x *WaitResponse) GetReportedState() string {
	if x != nil {
		return x.ReportedState
	}
	return ""
}

func (x *WaitResponse) GetReportedDetail() string {
	if x != nil {
		return x.ReportedDetail
	}
	return ""
}

func (x *WaitResponse) GetBusy() bool {
	if x != nil {
		return x.Busy
	}
	return false
}

func (x *WaitResponse) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *WaitResponse) GetState() SessionState {
	if x != nil {
		return x.State
	}
	return SessionState_SESSION_STATE_UNSPECIFIED
}

func (x *WaitResponse) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

type DoctorRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Act on the fixable findings rather than only reporting them.
	Repair bool `protobuf:"varint,1,opt,name=repair,proto3" json:"repair,omitempty"`
	// The calling client's build, so the server can report a mismatch with its own.
	//
	// Sent by the client rather than derived server-side, because that is the only place it is knowable: the
	// server cannot tell which binary connected to it. Empty from a client that predates this field, which
	// is itself a version difference worth reporting.
	ClientVersion string `protobuf:"bytes,2,opt,name=client_version,json=clientVersion,proto3" json:"client_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DoctorRequest) Reset() {
	*x = DoctorRequest{}
	mi := &file_cm_server_v1_server_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DoctorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DoctorRequest) ProtoMessage() {}

func (x *DoctorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cm_server_v1_server_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DoctorRequest.ProtoReflect.Descriptor instead.
func (*DoctorRequest) Descriptor() ([]byte, []int) {
	return file_cm_server_v1_server_proto_rawDescGZIP(), []int{8}
}

func (x *DoctorRequest) GetRepair() bool {
	if x != nil {
		return x.Repair
	}
	return false
}

func (x *DoctorRequest) GetClientVersion() string {
	if x != nil {
		return x.ClientVersion
	}
	return ""
}

type DoctorResponse struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Findings []*Finding             `protobuf:"bytes,1,rep,name=findings,proto3" json:"findings,omitempty"`
	// What a repair did, empty when repair was not requested.
	Repaired []string `protobuf:"bytes,2,rep,name=repaired,proto3" json:"repaired,omitempty"`
	// The server's own build, so a client can show both sides of a mismatch.
	ServerVersion string `protobuf:"bytes,3,opt,name=server_version,json=serverVersion,proto3" json:"server_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DoctorResponse) Reset() {
	*x = DoctorResponse{}
	mi := &file_cm_server_v1_server_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DoctorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DoctorResponse) ProtoMessage() {}

func (x *DoctorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cm_server_v1_server_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DoctorResponse.ProtoReflect.Descriptor instead.
func (*DoctorResponse) Descriptor() ([]byte, []int) {
	return file_cm_server_v1_server_proto_rawDescGZIP(), []int{9}
}

func (x *DoctorResponse) GetFindings() []*Finding {
	if x != nil {
		return x.Findings
	}
	return nil
}

func (x *DoctorResponse) GetRepaired() []string {
	if x != nil {
		return x.Repaired
	}
	return nil
}

func (x *DoctorResponse) GetServerVersion() string {
	if x != nil {
		return x.ServerVersion
	}
	return ""
}

// Finding is one thing wrong with an installation.
type Finding struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// A stable string rather than an enum, so a script matching on it keeps working as kinds are added:
	// "orphan-shim", "stale-socket", "missing-shim".
	Kind    string `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"`
	Session string `protobuf:"bytes,2,opt,name=session,proto3" json:"session,omitempty"`
	Socket  string `protobuf:"bytes,3,opt,name=socket,proto3" json:"socket,omitempty"`
	// Set when a shim answered and reported them.
	ShimPid       int32  `protobuf:"varint,4,opt,name=shim_pid,json=shimPid,proto3" json:"shim_pid,omitempty"`
	ShellPid      int32  `protobuf:"varint,5,opt,name=shell_pid,json=shellPid,proto3" json:"shell_pid,omitempty"`
	Detail        string `protobuf:"bytes,6,opt,name=detail,proto3" json:"detail,omitempty"`
	Fixable       bool   `protobuf:"varint,7,opt,name=fixable,proto3" json:"fixable,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Finding) Reset() {
	*x = Finding{}
	mi := &file_cm_server_v1_server_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Finding) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Finding) ProtoMessage() {}

func (x *Finding) ProtoReflect() protoreflect.Message {
	mi := &file_cm_server_v1_server_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Finding.ProtoReflect.Descriptor instead.
func (*Finding) Descriptor() ([]byte, []int) {
	return file_cm_server_v1_server_proto_rawDescGZIP(), []int{10}
}

func (x *Finding) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *Finding) GetSession() string {
	if x != nil {
		return x.Session
	}
	return ""
}

func (x *Finding) GetSocket() string {
	if x != nil {
		return x.Socket
	}
	return ""
}

func (x *Finding) GetShimPid() int32 {
	if x != nil {
		return x.ShimPid
	}
	return 0
}

func (x *Finding) GetShellPid() int32 {
	if x != nil {
		return x.ShellPid
	}
	return 0
}

func (x *Finding) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

func (x *Finding) GetFixable() bool {
	if x != nil {
		return x.Fixable
	}
	return false
}

type ShutdownRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShutdownRequest) Reset() {
	*x = ShutdownRequest{}
	mi := &file_cm_server_v1_server_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShutdownRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShutdownRequest) ProtoMessage() {}

func (x *ShutdownRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cm_server_v1_server_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShutdownRequest.ProtoReflect.Descriptor instead.
func (*ShutdownRequest) Descriptor() ([]byte, []int) {
	return file_cm_server_v1_server_proto_rawDescGZIP(), []int{11}
}

// ShutdownResponse confirms the server is stopping.
type ShutdownResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShutdownResponse) Reset() {
	*x = ShutdownResponse{}
	mi := &file_cm_server_v1_server_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShutdownResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShutdownResponse) ProtoMessage() {}

func (x *ShutdownResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cm_server_v1_server_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShutdownResponse.ProtoReflect.Descriptor instead.
func (*ShutdownResponse) Descriptor() ([]byte, []int) {
	return file_cm_server_v1_server_proto_rawDescGZIP(), []int{12}
}

// AttachRequest is a client-to-server event. The first message on the stream must be an
// Open; everything after it is input, a resize, or a detach.
type AttachRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Event:
	//
	//	*AttachRequest_Open
	//	*AttachRequest_Input
	//	*AttachRequest_Resize
	//	*AttachRequest_Detach
	Event         isAttachRequest_Event `protobuf_oneof:"event"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AttachRequest) Reset() {
	*x = AttachRequest{}
	mi := &file_cm_server_v1_server_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttachRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttachRequest) ProtoMessage() {}

func (x *AttachRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cm_server_v1_server_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttachRequest.ProtoReflect.Descriptor instead.
func (*AttachRequest) Descriptor() ([]byte, []int) {
	return file_cm_server_v1_server_proto_rawDescGZIP(), []int{13}
}

func (x *AttachRequest) GetEvent() isAttachRequest_Event {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *AttachRequest) GetOpen() *Open {
	if x != nil {
		if x, ok := x.Event.(*AttachRequest_Open); ok {
			return x.Open
		}
	}
	return nil
}

func (x *AttachRequest) GetInput() *Input {
	if x != nil {
		if x, ok := x.Event.(*AttachRequest_Input); ok {
			return x.Input
		}
	}
	return nil
}

func (x *AttachRequest) GetResize() *Resize {
	if x != nil {
		if x, ok := x.Event.(*AttachRequest_Resize); ok {
			return x.Resize
		}
	}
	return nil
}

func (x *AttachRequest) GetDetach() *Detach {
	if x != nil {
		if x, ok := x.Event.(*AttachRequest_Detach); ok {
			return x.Detach
		}
	}
	return nil
}

type isAttachRequest_Event interface {
	isAttachRequest_Event()
}

type AttachRequest_Open struct {
	Open *Open `protobuf:"bytes,1,opt,name=open,proto3,oneof"`
}

type AttachRequest_Input struct {
	Input *Input `protobuf:"bytes,2,opt,name=input,proto3,oneof"`
}

type AttachRequest_Resize struct {
	Resize *Resize `protobuf:"bytes,3,opt,name=resize,proto3,oneof"`
}

type AttachRequest_Detach struct {
	Detach *Detach `protobuf:"bytes,4,opt,name=detach,proto3,oneof"`
}

func (*AttachRequest_Open) isAttachRequest_Event() {}

func (*AttachRequest_Input) isAttachRequest_Event() {}

func (*AttachRequest_Resize) isAttachRequest_Event() {}

func (*AttachRequest_Detach) isAttachRequest_Event() {}

type Open struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Session to attach to. Empty asks the server to allocate a unique name, which is how
	// a terminal emulator creates a per-window session without inventing names itself.
	Session string `protobuf:"bytes,1,opt,name=session,proto3" json:"session,omitempty"`
	// Initial window size.
	Rows   uint32 `protobuf:"varint,2,opt,name=rows,proto3" json:"rows,omitempty"`
	Cols   uint32 `protobuf:"varint,3,opt,name=cols,proto3" json:"cols,omitempty"`
	XPixel uint32 `protobuf:"varint,4,opt,name=x_pixel,json=xPixel,proto3" json:"x_pixel,omitempty"`
	YPixel uint32 `protobuf:"varint,5,opt,name=y_pixel,json=yPixel,proto3" json:"y_pixel,omitempty"`
	// Resume output from this sequence number instead of restoring screen state. Set by a
	// client reconnecting after the server restarted: its terminal still shows the session,
	// so it wants the bytes it missed, not a fresh repaint. Absent on a first attach.
	ResumeFromSeq *uint64 `protobuf:"varint,6,opt,name=resume_from_seq,json=resumeFromSeq,proto3,oneof" json:"resume_from_seq,omitempty"`
	// Take ownership of the session: if this client's connection drops without sending a
	// Detach, the server terminates the session.
	//
	// This is what makes per-window sessions work without external cleanup. Closing a
	// terminal window kills its session, while detaching deliberately, or the server
	// restarting, leaves it running. Distinguishing those cases is exactly what a terminal
	// emulator cannot do reliably from the outside.
	Own bool `protobuf:"varint,7,opt,name=own,proto3" json:"own,omitempty"`
	// Attach without sending input or affecting sizing: a read-only follower.
	ReadOnly bool `protobuf:"varint,8,opt,name=read_only,json=readOnly,proto3" json:"read_only,omitempty"`
	// Command to run instead of the user's shell. Only meaningful when creating.
	Command []string `protobuf:"bytes,9,rep,name=command,proto3" json:"command,omitempty"`
	// Working directory for a newly created session. Empty means the client's cwd.
	Cwd string `protobuf:"bytes,10,opt,name=cwd,proto3" json:"cwd,omitempty"`
	// Environment variables to set for a newly created session, as KEY=VALUE.
	Env []string `protobuf:"bytes,11,rep,name=env,proto3" json:"env,omitempty"`
	// Terminal-related variables from this client's own environment, as KEY -> VALUE.
	//
	// Recorded on every attach, not just creation. A shell in a long-lived session holds values
	// describing the terminal that started it, and reattaching from a new terminal, or the same
	// one after it restarted, makes those stale. kitty's KITTY_LISTEN_ON is the sharp case, since
	// every kitten call goes through it.
	//
	// Distinct from env above, which sets variables for a shell being created. These are recorded
	// for an existing shell to ask about later.
	ClientEnv map[string]string `protobuf:"bytes,12,rep,name=client_env,json=clientEnv,proto3" json:"client_env,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Persist requests that this session's content survive a reboot, regardless of whether its name
	// matches the server's configured patterns.
	Persist bool `protobuf:"varint,13,opt,name=persist,proto3" json:"persist,omitempty"`
	// OnRestore overrides the server's configured behavior when reviving this session: "shell",
	// "none", or "command". Empty means the configured default.
	//
	// A string rather than an enum because it is a per-session override of a config value that is
	// also a string, and keeping one spelling avoids two vocabularies for the same setting.
	OnRestore string `protobuf:"bytes,14,opt,name=on_restore,json=onRestore,proto3" json:"on_restore,omitempty"`
	// CaptureOutput saves this session's output so it can be read after the session ends, without
	// asking for reboot survival.
	//
	// Distinct from persist because the two differ in how long the session is kept, not in mechanism.
	// `cm run` sets this so `cm history` works once the command has exited, while leaving the session
	// eligible for prompt cleanup rather than the week a persisted session is kept.
	CaptureOutput bool `protobuf:"varint,15,opt,name=capture_output,json=captureOutput,proto3" json:"capture_output,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Open) Reset() {
	*x = Open{}
	mi := &file_cm_server_v1_server_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Open) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Open) ProtoMessage() {}

func (x *Open) ProtoReflect() protoreflect.Message {
	mi := &file_cm_server_v1_server_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Open.ProtoReflect.Descriptor instead.
func (*Open) Descriptor() ([]byte, []int) {
	return file_cm_server_v1_server_proto_rawDescGZIP(), []int{14}
}

func (x *Open) GetSession() string {
	if x != nil {
		return x.Session
	}
	return ""
}

func (x *Open) GetRows() uint32 {
	if x != nil {
		return x.Rows
	}
	return 0
}

func (x *Open) GetCols() uint32 {
	if x != nil {
		return x.Cols
	}
	return 0
}

func (x *Open) GetXPixel() uint32 {
	if x != nil {
		return x.XPixel
	}
	return 0
}

func (x *Open) GetYPixel() uint32 {
	if x != nil {
		return x.YPixel
	}
	return 0
}

func (x *Open) GetResumeFromSeq() uint64 {
	if x != nil && x.ResumeFromSeq != nil {
		return *x.ResumeFromSeq
	}
	return 0
}

func (x *Open) GetOwn() bool {
	if x != nil {
		return x.Own
	}
	return false
}

func (x *Open) GetReadOnly() bool {
	if x != nil {
		return x.ReadOnly
	}
	return false
}

func (x *Open) GetCommand() []string {
	if x != nil {
		return x.Command
	}
	return nil
}

func (x *Open) GetCwd() string {
	if x != nil {
		return x.Cwd
	}
	return ""
}

func (x *Open) GetEnv() []string {
	if x != nil {
		return x.Env
	}
	return nil
}

func (x *Open) GetClientEnv() map[string]string {
	if x != nil {
		return x.ClientEnv
	}
	return nil
}

func (x *Open) GetPersist() bool {
	if x != nil {
		return x.Persist
	}
	return false
}

func (x *Open) GetOnRestore() string {
	if x != nil {
		return x.OnRestore
	}
	return ""
}

func (x *Open) GetCaptureOutput() bool {
	if x != nil {
		return x.CaptureOutput
	}
	return false
}

type Input struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Input) Reset() {
	*x = Input{}
	mi := &file_cm_server_v1_server_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Input) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Input) ProtoMessage() {}

func (x *Input) ProtoReflect() protoreflect.Message {
	mi := &file_cm_server_v1_server_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Input.ProtoReflect.Descriptor instead.
func (*Input) Descriptor() ([]byte, []int) {
	return file_cm_server_v1_server_proto_rawDescGZIP(), []int{15}
}

func (x *Input) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type Resize struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rows          uint32                 `protobuf:"varint,1,opt,name=rows,proto3" json:"rows,omitempty"`
	Cols          uint32                 `protobuf:"varint,2,opt,name=cols,proto3" json:"cols,omitempty"`
	XPixel        uint32                 `protobuf:"varint,3,opt,name=x_pixel,json=xPixel,proto3" json:"x_pixel,omitempty"`
	YPixel        uint32                 `protobuf:"varint,4,opt,name=y_pixel,json=yPixel,proto3" json:"y_pixel,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Resize) Reset() {
	*x = Resize{}
	mi := &file_cm_server_v1_server_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Resize) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Resize) ProtoMessage() {}

func (x *Resize) ProtoReflect() protoreflect.Message {
	mi := &file_cm_server_v1_server_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Resize.ProtoReflect.Descriptor instead.
func (*Resize) Descriptor() ([]byte, []int) {
	return file_cm_server_v1_server_proto_rawDescGZIP(), []int{16}
}

func (x *Resize) GetRows() uint32 {
	if x != nil {
		return x.Rows
	}
	return 0
}

func (x *Resize) GetCols() uint32 {
	if x != nil {
		return x.Cols
	}
	return 0
}

func (x *Resize) GetXPixel() uint32 {
	if x != nil {
		return x.XPixel
	}
	return 0
}

func (x *Resize) GetYPixel() uint32 {
	if x != nil {
		return x.YPixel
	}
	return 0
}

// Detach ends this client's attachment without terminating the session. Sending it
// explicitly is what distinguishes leaving a session from losing the connection, so an
// owning client's session survives a deliberate detach.
type Detach struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Detach) Reset() {
	*x = Detach{}
	mi := &file_cm_server_v1_server_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Detach) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Detach) ProtoMessage() {}

func (x *Detach) ProtoReflect() protoreflect.Message {
	mi := &file_cm_server_v1_server_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Detach.ProtoReflect.Descriptor instead.
func (*Detach) Descriptor() ([]byte, []int) {
	return file_cm_server_v1_server_proto_rawDescGZIP(), []int{17}
}

// AttachResponse is a server-to-client event.
type AttachResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Event:
	//
	//	*AttachResponse_Opened
	//	*AttachResponse_Output
	//	*AttachResponse_Exited
	//	*AttachResponse_Metadata
	//	*AttachResponse_Detached
	Event         isAttachResponse_Event `protobuf_oneof:"event"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AttachResponse) Reset() {
	*x = AttachResponse{}
	mi := &file_cm_server_v1_server_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttachResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttachResponse) ProtoMessage() {}

func (x *AttachResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cm_server_v1_server_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttachResponse.ProtoReflect.Descriptor instead.
func (*AttachResponse) Descriptor() ([]byte, []int) {
	return file_cm_server_v1_server_proto_rawDescGZIP(), []int{18}
}

func (x *AttachResponse) GetEvent() isAttachResponse_Event {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *AttachResponse) GetOpened() *Opened {
	if x != nil {
		if x, ok := x.Event.(*AttachResponse_Opened); ok {
			return x.Opened
		}
	}
	return nil
}

func (x *AttachResponse) GetOutput() *Output {
	if x != nil {
		if x, ok := x.Event.(*AttachResponse_Output); ok {
			return x.Output
		}
	}
	return nil
}

func (x *AttachResponse) GetExited() *Exited {
	if x != nil {
		if x, ok := x.Event.(*AttachResponse_Exited); ok {
			return x.Exited
		}
	}
	return nil
}

func (x *AttachResponse) GetMetadata() *Metadata {
	if x != nil {
		if x, ok := x.Event.(*AttachResponse_Metadata); ok {
			return x.Metadata
		}
	}
	return nil
}

func (x *AttachResponse) GetDetached() *Detached {
	if x != nil {
		if x, ok := x.Event.(*AttachResponse_Detached); ok {
			return x.Detached
		}
	}
	return nil
}

type isAttachResponse_Event interface {
	isAttachResponse_Event()
}

type AttachResponse_Opened struct {
	Opened *Opened `protobuf:"bytes,1,opt,name=opened,proto3,oneof"`
}

type AttachResponse_Output struct {
	Output *Output `protobuf:"bytes,2,opt,name=output,proto3,oneof"`
}

type AttachResponse_Exited struct {
	Exited *Exited `protobuf:"bytes,3,opt,name=exited,proto3,oneof"`
}

type AttachResponse_Metadata struct {
	Metadata *Metadata `protobuf:"bytes,4,opt,name=metadata,proto3,oneof"`
}

type AttachResponse_Detached struct {
	Detached *Detached `protobuf:"bytes,5,opt,name=detached,proto3,oneof"`
}

func (*AttachResponse_Opened) isAttachResponse_Event() {}

func (*AttachResponse_Output) isAttachResponse_Event() {}

func (*AttachResponse_Exited) isAttachResponse_Event() {}

func (*AttachResponse_Metadata) isAttachResponse_Event() {}

func (*AttachResponse_Detached) isAttachResponse_Event() {}

// Detached confirms the server processed a client's Detach.
//
// A client must wait for this before exiting. Sending Detach and returning immediately does not work:
// the send is asynchronous, so the connection is torn down before the message is transmitted, and the
// server then sees a client that vanished without detaching. For an owned session that means being
// destroyed, which is the opposite of what detaching asks for.
type Detached struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Detached) Reset() {
	*x = Detached{}
	mi := &file_cm_server_v1_server_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Detached) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Detached) ProtoMessage() {}

func (x *Detached) ProtoReflect() protoreflect.Message {
	mi := &file_cm_server_v1_server_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Detached.ProtoReflect.Descriptor instead.
func (*Detached) Descriptor() ([]byte, []int) {
	return file_cm_server_v1_server_proto_rawDescGZIP(), []int{19}
}

// Metadata reports what the shell has said about itself, so a client can act on it.
//
// A terminal emulator needs this: retitling a tab, or opening a new window in the session's
// directory, requires knowing values that the shell reported to the multiplexer rather than to the
// terminal. Sent on attach and whenever a value changes.
type Metadata struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Title string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	// Working directory, decoded from OSC 7 rather than the raw URI the shell sent.
	Cwd string `protobuf:"bytes,2,opt,name=cwd,proto3" json:"cwd,omitempty"`
	// Whether cwd exists on the client's machine. False once a session has ssh'd elsewhere, in
	// which case acting on the path locally is wrong.
	CwdIsLocal bool `protobuf:"varint,3,opt,name=cwd_is_local,json=cwdIsLocal,proto3" json:"cwd_is_local,omitempty"`
	// Whether a command is running, and which one, from OSC 133. See the same fields on Session.
	//
	// Forwarded as an event rather than left to polling so a terminal emulator can react as it happens,
	// which is the difference between a tab that shows what is running and one that shows it a second
	// later.
	Busy    bool   `protobuf:"varint,4,opt,name=busy,proto3" json:"busy,omitempty"`
	Command string `protobuf:"bytes,5,opt,name=command,proto3" json:"command,omitempty"`
	// What a program in the session reported about itself, which takes precedence over busy above.
	ReportedState  string `protobuf:"bytes,6,opt,name=reported_state,json=reportedState,proto3" json:"reported_state,omitempty"`
	ReportedDetail string `protobuf:"bytes,7,opt,name=reported_detail,json=reportedDetail,proto3" json:"reported_detail,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Metadata) Reset() {
	*x = Metadata{}
	mi := &file_cm_server_v1_server_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Metadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Metadata) ProtoMessage() {}

func (x *Metadata) ProtoReflect() protoreflect.Message {
	mi := &file_cm_server_v1_server_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Metadata.ProtoReflect.Descriptor instead.
func (*Metadata) Descriptor() ([]byte, []int) {
	return file_cm_server_v1_server_proto_rawDescGZIP(), []int{20}
}

func (x *Metadata) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Metadata) GetCwd() string {
	if x != nil {
		return x.Cwd
	}
	return ""
}

func (x *Metadata) GetCwdIsLocal() bool {
	if x != nil {
		return x.CwdIsLocal
	}
	return false
}

func (x *Metadata) GetBusy() bool {
	if x != nil {
		return x.Busy
	}
	return false
}

func (x *Metadata) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *Metadata) GetReportedState() string {
	if x != nil {
		return x.ReportedState
	}
	return ""
}

func (x *Metadata) GetReportedDetail() string {
	if x != nil {
		return x.ReportedDetail
	}
	return ""
}

type Opened struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Resolved session name, which the client needs when it asked the server to allocate
	// one.
	Session string `protobuf:"bytes,1,opt,name=session,proto3" json:"session,omitempty"`
	// Whether this call created the session.
	Created bool `protobuf:"varint,2,opt,name=created,proto3" json:"created,omitempty"`
	// Bytes to write to the terminal before streaming output: either serialized screen
	// state on a fresh attach, or nothing when resuming.
	Restore []byte `protobuf:"bytes,3,opt,name=restore,proto3" json:"restore,omitempty"`
	// Sequence number the following output stream starts at. A client tracks this so it can
	// resume from the right place after a reconnect.
	NextSeq       uint64 `protobuf:"varint,4,opt,name=next_seq,json=nextSeq,proto3" json:"next_seq,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Opened) Reset() {
	*x = Opened{}
	mi := &file_cm_server_v1_server_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Opened) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Opened) ProtoMessage() {}

func (x *Opened) ProtoReflect() protoreflect.Message {
	mi := &file_cm_server_v1_server_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Opened.ProtoReflect.Descriptor instead.
func (*Opened) Descriptor() ([]byte, []int) {
	return file_cm_server_v1_server_proto_rawDescGZIP(), []int{21}
}

func (x *Opened) GetSession() string {
	if x != nil {
		return x.Session
	}
	return ""
}

func (x *Opened) GetCreated() bool {
	if x != nil {
		return x.Created
	}
	return false
}

func (x *Opened) GetRestore() []byte {
	if x != nil {
		return x.Restore
	}
	return nil
}

func (x *Opened) GetNextSeq() uint64 {
	if x != nil {
		return x.NextSeq
	}
	return 0
}

type Output struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Seq   uint64                 `protobuf:"varint,1,opt,name=seq,proto3" json:"seq,omitempty"`
	Data  []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	// Set when output was truncated before the requested sequence, so the client knows its
	// view has a hole and should reattach fresh rather than assume continuity.
	Gap           bool `protobuf:"varint,3,opt,name=gap,proto3" json:"gap,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Output) Reset() {
	*x = Output{}
	mi := &file_cm_server_v1_server_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Output) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Output) ProtoMessage() {}

func (x *Output) ProtoReflect() protoreflect.Message {
	mi := &file_cm_server_v1_server_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Output.ProtoReflect.Descriptor instead.
func (*Output) Descriptor() ([]byte, []int) {
	return file_cm_server_v1_server_proto_rawDescGZIP(), []int{22}
}

func (x *Output) GetSeq() uint64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *Output) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *Output) GetGap() bool {
	if x != nil {
		return x.Gap
	}
	return false
}

// Exited reports that the session's shell exited, so the client should stop rather than
// try to reconnect.
type Exited struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExitCode      int32                  `protobuf:"varint,1,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Exited) Reset() {
	*x = Exited{}
	mi := &file_cm_server_v1_server_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Exited) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Exited) ProtoMessage() {}

func (x *Exited) ProtoReflect() protoreflect.Message {
	mi := &file_cm_server_v1_server_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Exited.ProtoReflect.Descriptor instead.
func (*Exited) Descriptor() ([]byte, []int) {
	return file_cm_server_v1_server_proto_rawDescGZIP(), []int{23}
}

func (x *Exited) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

type ListRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Only sessions whose name matches this prefix. Empty matches all.
	Prefix        string `protobuf:"bytes,1,opt,name=prefix,proto3" json:"prefix,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRequest) Reset() {
	*x = ListRequest{}
	mi := &file_cm_server_v1_server_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRequest) ProtoMessage() {}

func (x *ListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cm_server_v1_server_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRequest.ProtoReflect.Descriptor instead.
func (*ListRequest) Descriptor() ([]byte, []int) {
	return file_cm_server_v1_server_proto_rawDescGZIP(), []int{24}
}

func (x *ListRequest) GetPrefix() string {
	if x != nil {
		return x.Prefix
	}
	return ""
}

type ListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sessions      []*Session             `protobuf:"bytes,1,rep,name=sessions,proto3" json:"sessions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListResponse) Reset() {
	*x = ListResponse{}
	mi := &file_cm_server_v1_server_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListResponse) ProtoMessage() {}

func (x *ListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cm_server_v1_server_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListResponse.ProtoReflect.Descriptor instead.
func (*ListResponse) Descriptor() ([]byte, []int) {
	return file_cm_server_v1_server_proto_rawDescGZIP(), []int{25}
}

func (x *ListResponse) GetSessions() []*Session {
	if x != nil {
		return x.Sessions
	}
	return nil
}

type Session struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Name     string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	ShellPid int32                  `protobuf:"varint,2,opt,name=shell_pid,json=shellPid,proto3" json:"shell_pid,omitempty"`
	// Number of attached clients.
	Clients uint32 `protobuf:"varint,3,opt,name=clients,proto3" json:"clients,omitempty"`
	// Working directory, as reported by the shell via OSC 7. May be empty if the shell
	// does not report it.
	Cwd string `protobuf:"bytes,4,opt,name=cwd,proto3" json:"cwd,omitempty"`
	// Whether cwd is on this host. A session that has ssh'd elsewhere reports a path that
	// does not exist locally, so acting on it, such as opening a new window there, is
	// wrong.
	CwdIsLocal    bool   `protobuf:"varint,5,opt,name=cwd_is_local,json=cwdIsLocal,proto3" json:"cwd_is_local,omitempty"`
	Title         string `protobuf:"bytes,6,opt,name=title,proto3" json:"title,omitempty"`
	CreatedAtUnix int64  `protobuf:"varint,7,opt,name=created_at_unix,json=createdAtUnix,proto3" json:"created_at_unix,omitempty"`
	Exited        bool   `protobuf:"varint,8,opt,name=exited,proto3" json:"exited,omitempty"`
	ExitCode      int32  `protobuf:"varint,9,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	// Lifecycle stage. Preferred over exited, which cannot distinguish a shell that exited from a
	// shim that vanished; exited remains for compatibility.
	State SessionState `protobuf:"varint,10,opt,name=state,proto3,enum=cm.server.v1.SessionState" json:"state,omitempty"`
	// Working directory as the shell reported it, which is a URI for OSC 7 and keeps the host, so a
	// caller can tell a remote directory from a local one. cwd holds the decoded local path.
	CwdUri string `protobuf:"bytes,11,opt,name=cwd_uri,json=cwdUri,proto3" json:"cwd_uri,omitempty"`
	// What a program in the session reported about itself, if anything: "idle", "busy", or "blocked".
	//
	// Empty when nothing has reported, in which case busy below is what cm derived from the shell. When
	// both are present this one wins, since a program describing itself is better evidence than a shell
	// marker.
	ReportedState string `protobuf:"bytes,14,opt,name=reported_state,json=reportedState,proto3" json:"reported_state,omitempty"`
	// The note that came with the report, and who sent it. Both optional and free-form.
	ReportedDetail string `protobuf:"bytes,15,opt,name=reported_detail,json=reportedDetail,proto3" json:"reported_detail,omitempty"`
	ReportedSource string `protobuf:"bytes,16,opt,name=reported_source,json=reportedSource,proto3" json:"reported_source,omitempty"`
	// Whether a command is running, as opposed to the shell sitting at a prompt, from OSC 133.
	//
	// A terminal emulator needs this to decide whether closing a window is destructive: the shell owns
	// the pty, so kitty only ever sees `cm attach` running and cannot tell a busy session from an idle
	// one. False for a shell with no OSC 133 support, since nothing then reports otherwise.
	Busy bool `protobuf:"varint,12,opt,name=busy,proto3" json:"busy,omitempty"`
	// The command line the shell reported running, when it reported one.
	//
	// Best effort: the cmdline parameter is an extension that zsh and bash send under kitty's shell
	// integration and other shells omit, so this can be empty while busy is true.
	Command       string `protobuf:"bytes,13,opt,name=command,proto3" json:"command,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Session) Reset() {
	*x = Session{}
	mi := &file_cm_server_v1_server_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Session) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Session) ProtoMessage() {}

func (x *Session) ProtoReflect() protoreflect.Message {
	mi := &file_cm_server_v1_server_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Session.ProtoReflect.Descriptor instead.
func (*Session) Descriptor() ([]byte, []int) {
	return file_cm_server_v1_server_proto_rawDescGZIP(), []int{26}
}

func (x *Session) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Session) GetShellPid() int32 {
	if x != nil {
		return x.ShellPid
	}
	return 0
}

func (x *Session) GetClients() uint32 {
	if x != nil {
		return x.Clients
	}
	return 0
}

func (x *Session) GetCwd() string {
	if x != nil {
		return x.Cwd
	}
	return ""
}

func (x *Session) GetCwdIsLocal() bool {
	if x != nil {
		return x.CwdIsLocal
	}
	return false
}

func (x *Session) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Session) GetCreatedAtUnix() int64 {
	if x != nil {
		return x.CreatedAtUnix
	}
	return 0
}

func (x *Session) GetExited() bool {
	if x != nil {
		return x.Exited
	}
	return false
}

func (x *Session) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

func (x *Session) GetState() SessionState {
	if x != nil {
		return x.State
	}
	return SessionState_SESSION_STATE_UNSPECIFIED
}

func (x *Session) GetCwdUri() string {
	if x != nil {
		return x.CwdUri
	}
	return ""
}

func (x *Session) GetReportedState() string {
	if x != nil {
		return x.ReportedState
	}
	return ""
}

func (x *Session) GetReportedDetail() string {
	if x != nil {
		return x.ReportedDetail
	}
	return ""
}

func (x *Session) GetReportedSource() string {
	if x != nil {
		return x.ReportedSource
	}
	return ""
}

func (x *Session) GetBusy() bool {
	if x != nil {
		return x.Busy
	}
	return false
}

func (x *Session) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

type KillRequest struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Sessions []string               `protobuf:"bytes,1,rep,name=sessions,proto3" json:"sessions,omitempty"`
	// Remove the session record even if its shim cannot be reached. Without this, an
	// unreachable shim is left alone: it may be busy rather than dead, and discarding the
	// record would orphan it permanently.
	Force         bool `protobuf:"varint,2,opt,name=force,proto3" json:"force,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KillRequest) Reset() {
	*x = KillRequest{}
	mi := &file_cm_server_v1_server_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KillRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KillRequest) ProtoMessage() {}

func (x *KillRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cm_server_v1_server_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KillRequest.ProtoReflect.Descriptor instead.
func (*KillRequest) Descriptor() ([]byte, []int) {
	return file_cm_server_v1_server_proto_rawDescGZIP(), []int{27}
}

func (x *KillRequest) GetSessions() []string {
	if x != nil {
		return x.Sessions
	}
	return nil
}

func (x *KillRequest) GetForce() bool {
	if x != nil {
		return x.Force
	}
	return false
}

type KillResponse struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Killed []string               `protobuf:"bytes,1,rep,name=killed,proto3" json:"killed,omitempty"`
	// Sessions that could not be killed, keyed by name.
	Errors        map[string]string `protobuf:"bytes,2,rep,name=errors,proto3" json:"errors,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KillResponse) Reset() {
	*x = KillResponse{}
	mi := &file_cm_server_v1_server_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KillResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KillResponse) ProtoMessage() {}

func (x *KillResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cm_server_v1_server_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KillResponse.ProtoReflect.Descriptor instead.
func (*KillResponse) Descriptor() ([]byte, []int) {
	return file_cm_server_v1_server_proto_rawDescGZIP(), []int{28}
}

func (x *KillResponse) GetKilled() []string {
	if x != nil {
		return x.Killed
	}
	return nil
}

func (x *KillResponse) GetErrors() map[string]string {
	if x != nil {
		return x.Errors
	}
	return nil
}

type SendRequest struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Session string                 `protobuf:"bytes,1,opt,name=session,proto3" json:"session,omitempty"`
	Data    []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	// Wait for a state after delivering the input, in the same request.
	//
	// One request rather than a send followed by a wait, because the two cannot be ordered from outside:
	// a command that finishes before the second call arrives leaves the caller waiting for a transition
	// that already happened. The server arms the wait before it writes the input, so there is no window.
	WaitUntil     WaitState `protobuf:"varint,3,opt,name=wait_until,json=waitUntil,proto3,enum=cm.server.v1.WaitState" json:"wait_until,omitempty"`
	WaitTimeoutMs uint64    `protobuf:"varint,4,opt,name=wait_timeout_ms,json=waitTimeoutMs,proto3" json:"wait_timeout_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendRequest) Reset() {
	*x = SendRequest{}
	mi := &file_cm_server_v1_server_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendRequest) ProtoMessage() {}

func (x *SendRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cm_server_v1_server_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendRequest.ProtoReflect.Descriptor instead.
func (*SendRequest) Descriptor() ([]byte, []int) {
	return file_cm_server_v1_server_proto_rawDescGZIP(), []int{29}
}

func (x *SendRequest) GetSession() string {
	if x != nil {
		return x.Session
	}
	return ""
}

func (x *SendRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *SendRequest) GetWaitUntil() WaitState {
	if x != nil {
		return x.WaitUntil
	}
	return WaitState_WAIT_STATE_UNSPECIFIED
}

func (x *SendRequest) GetWaitTimeoutMs() uint64 {
	if x != nil {
		return x.WaitTimeoutMs
	}
	return 0
}

type SendResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Present only when wait_until was set. Reports the same thing Wait does.
	Wait          *WaitResponse `protobuf:"bytes,1,opt,name=wait,proto3" json:"wait,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendResponse) Reset() {
	*x = SendResponse{}
	mi := &file_cm_server_v1_server_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendResponse) ProtoMessage() {}

func (x *SendResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cm_server_v1_server_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendResponse.ProtoReflect.Descriptor instead.
func (*SendResponse) Descriptor() ([]byte, []int) {
	return file_cm_server_v1_server_proto_rawDescGZIP(), []int{30}
}

func (x *SendResponse) GetWait() *WaitResponse {
	if x != nil {
		return x.Wait
	}
	return nil
}

type HistoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Session       string                 `protobuf:"bytes,1,opt,name=session,proto3" json:"session,omitempty"`
	Format        HistoryFormat          `protobuf:"varint,2,opt,name=format,proto3,enum=cm.server.v1.HistoryFormat" json:"format,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HistoryRequest) Reset() {
	*x = HistoryRequest{}
	mi := &file_cm_server_v1_server_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HistoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HistoryRequest) ProtoMessage() {}

func (x *HistoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cm_server_v1_server_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HistoryRequest.ProtoReflect.Descriptor instead.
func (*HistoryRequest) Descriptor() ([]byte, []int) {
	return file_cm_server_v1_server_proto_rawDescGZIP(), []int{31}
}

func (x *HistoryRequest) GetSession() string {
	if x != nil {
		return x.Session
	}
	return ""
}

func (x *HistoryRequest) GetFormat() HistoryFormat {
	if x != nil {
		return x.Format
	}
	return HistoryFormat_HISTORY_FORMAT_UNSPECIFIED
}

type HistoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HistoryResponse) Reset() {
	*x = HistoryResponse{}
	mi := &file_cm_server_v1_server_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HistoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HistoryResponse) ProtoMessage() {}

func (x *HistoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cm_server_v1_server_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HistoryResponse.ProtoReflect.Descriptor instead.
func (*HistoryResponse) Descriptor() ([]byte, []int) {
	return file_cm_server_v1_server_proto_rawDescGZIP(), []int{32}
}

func (x *HistoryResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type GetEnvRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Session       string                 `protobuf:"bytes,1,opt,name=session,proto3" json:"session,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEnvRequest) Reset() {
	*x = GetEnvRequest{}
	mi := &file_cm_server_v1_server_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEnvRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEnvRequest) ProtoMessage() {}

func (x *GetEnvRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cm_server_v1_server_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEnvRequest.ProtoReflect.Descriptor instead.
func (*GetEnvRequest) Descriptor() ([]byte, []int) {
	return file_cm_server_v1_server_proto_rawDescGZIP(), []int{33}
}

func (x *GetEnvRequest) GetSession() string {
	if x != nil {
		return x.Session
	}
	return ""
}

type GetEnvResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Variables the latest client reported, as KEY -> VALUE.
	Env           map[string]string `protobuf:"bytes,1,rep,name=env,proto3" json:"env,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEnvResponse) Reset() {
	*x = GetEnvResponse{}
	mi := &file_cm_server_v1_server_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEnvResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEnvResponse) ProtoMessage() {}

func (x *GetEnvResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cm_server_v1_server_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEnvResponse.ProtoReflect.Descriptor instead.
func (*GetEnvResponse) Descriptor() ([]byte, []int) {
	return file_cm_server_v1_server_proto_rawDescGZIP(), []int{34}
}

func (x *GetEnvResponse) GetEnv() map[string]string {
	if x != nil {
		return x.Env
	}
	return nil
}

var File_cm_server_v1_server_proto protoreflect.FileDescriptor

const file_cm_server_v1_server_proto_rawDesc = "" +
	"\n" +
	"\x19cm/server/v1/server.proto\x12\fcm.server.v1\"\x0f\n" +
	"\rStatusRequest\"\xd1\x02\n" +
	"\x0eStatusResponse\x12\x10\n" +
	"\x03pid\x18\x01 \x01(\x05R\x03pid\x12&\n" +
	"\x0fstarted_at_unix\x18\x02 \x01(\x03R\rstartedAtUnix\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\x12\x1f\n" +
	"\vruntime_dir\x18\x04 \x01(\tR\n" +
	"runtimeDir\x12\x1b\n" +
	"\tstate_dir\x18\x05 \x01(\tR\bstateDir\x12)\n" +
	"\x10sessions_running\x18\x06 \x01(\x05R\x0fsessionsRunning\x12'\n" +
	"\x0fsessions_exited\x18\a \x01(\x05R\x0esessionsExited\x12#\n" +
	"\rsessions_dead\x18\b \x01(\x05R\fsessionsDead\x12\x18\n" +
	"\aclients\x18\t \x01(\x05R\aclients\x12\x1a\n" +
	"\bterminal\x18\n" +
	" \x01(\bR\bterminal\"\x8c\x01\n" +
	"\rReportRequest\x12\x18\n" +
	"\asession\x18\x01 \x01(\tR\asession\x121\n" +
	"\x05state\x18\x02 \x01(\x0e2\x1b.cm.server.v1.ReportedStateR\x05state\x12\x16\n" +
	"\x06detail\x18\x03 \x01(\tR\x06detail\x12\x16\n" +
	"\x06source\x18\x04 \x01(\tR\x06source\"\x10\n" +
	"\x0eReportResponse\"U\n" +
	"\vReadRequest\x12\x18\n" +
	"\asession\x18\x01 \x01(\tR\asession\x12\x14\n" +
	"\x05lines\x18\x02 \x01(\rR\x05lines\x12\x16\n" +
	"\x06unwrap\x18\x03 \x01(\bR\x06unwrap\"\"\n" +
	"\fReadResponse\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\"u\n" +
	"\vWaitRequest\x12\x18\n" +
	"\asession\x18\x01 \x01(\tR\asession\x12-\n" +
	"\x05until\x18\x02 \x01(\x0e2\x17.cm.server.v1.WaitStateR\x05until\x12\x1d\n" +
	"\n" +
	"timeout_ms\x18\x03 \x01(\x04R\ttimeoutMs\"\xf9\x01\n" +
	"\fWaitResponse\x12\x1c\n" +
	"\tsatisfied\x18\x01 \x01(\bR\tsatisfied\x12%\n" +
	"\x0ereported_state\x18\x06 \x01(\tR\rreportedState\x12'\n" +
	"\x0freported_detail\x18\a \x01(\tR\x0ereportedDetail\x12\x12\n" +
	"\x04busy\x18\x02 \x01(\bR\x04busy\x12\x18\n" +
	"\acommand\x18\x03 \x01(\tR\acommand\x120\n" +
	"\x05state\x18\x04 \x01(\x0e2\x1a.cm.server.v1.SessionStateR\x05state\x12\x1b\n" +
	"\texit_code\x18\x05 \x01(\x05R\bexitCode\"N\n" +
	"\rDoctorRequest\x12\x16\n" +
	"\x06repair\x18\x01 \x01(\bR\x06repair\x12%\n" +
	"\x0eclient_version\x18\x02 \x01(\tR\rclientVersion\"\x86\x01\n" +
	"\x0eDoctorResponse\x121\n" +
	"\bfindings\x18\x01 \x03(\v2\x15.cm.server.v1.FindingR\bfindings\x12\x1a\n" +
	"\brepaired\x18\x02 \x03(\tR\brepaired\x12%\n" +
	"\x0eserver_version\x18\x03 \x01(\tR\rserverVersion\"\xb9\x01\n" +
	"\aFinding\x12\x12\n" +
	"\x04kind\x18\x01 \x01(\tR\x04kind\x12\x18\n" +
	"\asession\x18\x02 \x01(\tR\asession\x12\x16\n" +
	"\x06socket\x18\x03 \x01(\tR\x06socket\x12\x19\n" +
	"\bshim_pid\x18\x04 \x01(\x05R\ashimPid\x12\x1b\n" +
	"\tshell_pid\x18\x05 \x01(\x05R\bshellPid\x12\x16\n" +
	"\x06detail\x18\x06 \x01(\tR\x06detail\x12\x18\n" +
	"\afixable\x18\a \x01(\bR\afixable\"\x11\n" +
	"\x0fShutdownRequest\"\x12\n" +
	"\x10ShutdownResponse\"\xcf\x01\n" +
	"\rAttachRequest\x12(\n" +
	"\x04open\x18\x01 \x01(\v2\x12.cm.server.v1.OpenH\x00R\x04open\x12+\n" +
	"\x05input\x18\x02 \x01(\v2\x13.cm.server.v1.InputH\x00R\x05input\x12.\n" +
	"\x06resize\x18\x03 \x01(\v2\x14.cm.server.v1.ResizeH\x00R\x06resize\x12.\n" +
	"\x06detach\x18\x04 \x01(\v2\x14.cm.server.v1.DetachH\x00R\x06detachB\a\n" +
	"\x05event\"\x88\x04\n" +
	"\x04Open\x12\x18\n" +
	"\asession\x18\x01 \x01(\tR\asession\x12\x12\n" +
	"\x04rows\x18\x02 \x01(\rR\x04rows\x12\x12\n" +
	"\x04cols\x18\x03 \x01(\rR\x04cols\x12\x17\n" +
	"\ax_pixel\x18\x04 \x01(\rR\x06xPixel\x12\x17\n" +
	"\ay_pixel\x18\x05 \x01(\rR\x06yPixel\x12+\n" +
	"\x0fresume_from_seq\x18\x06 \x01(\x04H\x00R\rresumeFromSeq\x88\x01\x01\x12\x10\n" +
	"\x03own\x18\a \x01(\bR\x03own\x12\x1b\n" +
	"\tread_only\x18\b \x01(\bR\breadOnly\x12\x18\n" +
	"\acommand\x18\t \x03(\tR\acommand\x12\x10\n" +
	"\x03cwd\x18\n" +
	" \x01(\tR\x03cwd\x12\x10\n" +
	"\x03env\x18\v \x03(\tR\x03env\x12@\n" +
	"\n" +
	"client_env\x18\f \x03(\v2!.cm.server.v1.Open.ClientEnvEntryR\tclientEnv\x12\x18\n" +
	"\apersist\x18\r \x01(\bR\apersist\x12\x1d\n" +
	"\n" +
	"on_restore\x18\x0e \x01(\tR\tonRestore\x12%\n" +
	"\x0ecapture_output\x18\x0f \x01(\bR\rcaptureOutput\x1a<\n" +
	"\x0eClientEnvEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\x12\n" +
	"\x10_resume_from_seq\"\x1b\n" +
	"\x05Input\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\"b\n" +
	"\x06Resize\x12\x12\n" +
	"\x04rows\x18\x01 \x01(\rR\x04rows\x12\x12\n" +
	"\x04cols\x18\x02 \x01(\rR\x04cols\x12\x17\n" +
	"\ax_pixel\x18\x03 \x01(\rR\x06xPixel\x12\x17\n" +
	"\ay_pixel\x18\x04 \x01(\rR\x06yPixel\"\b\n" +
	"\x06Detach\"\x95\x02\n" +
	"\x0eAttachResponse\x12.\n" +
	"\x06opened\x18\x01 \x01(\v2\x14.cm.server.v1.OpenedH\x00R\x06opened\x12.\n" +
	"\x06output\x18\x02 \x01(\v2\x14.cm.server.v1.OutputH\x00R\x06output\x12.\n" +
	"\x06exited\x18\x03 \x01(\v2\x14.cm.server.v1.ExitedH\x00R\x06exited\x124\n" +
	"\bmetadata\x18\x04 \x01(\v2\x16.cm.server.v1.MetadataH\x00R\bmetadata\x124\n" +
	"\bdetached\x18\x05 \x01(\v2\x16.cm.server.v1.DetachedH\x00R\bdetachedB\a\n" +
	"\x05event\"\n" +
	"\n" +
	"\bDetached\"\xd2\x01\n" +
	"\bMetadata\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12\x10\n" +
	"\x03cwd\x18\x02 \x01(\tR\x03cwd\x12 \n" +
	"\fcwd_is_local\x18\x03 \x01(\bR\n" +
	"cwdIsLocal\x12\x12\n" +
	"\x04busy\x18\x04 \x01(\bR\x04busy\x12\x18\n" +
	"\acommand\x18\x05 \x01(\tR\acommand\x12%\n" +
	"\x0ereported_state\x18\x06 \x01(\tR\rreportedState\x12'\n" +
	"\x0freported_detail\x18\a \x01(\tR\x0ereportedDetail\"q\n" +
	"\x06Opened\x12\x18\n" +
	"\asession\x18\x01 \x01(\tR\asession\x12\x18\n" +
	"\acreated\x18\x02 \x01(\bR\acreated\x12\x18\n" +
	"\arestore\x18\x03 \x01(\fR\arestore\x12\x19\n" +
	"\bnext_seq\x18\x04 \x01(\x04R\anextSeq\"@\n" +
	"\x06Output\x12\x10\n" +
	"\x03seq\x18\x01 \x01(\x04R\x03seq\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\x12\x10\n" +
	"\x03gap\x18\x03 \x01(\bR\x03gap\"%\n" +
	"\x06Exited\x12\x1b\n" +
	"\texit_code\x18\x01 \x01(\x05R\bexitCode\"%\n" +
	"\vListRequest\x12\x16\n" +
	"\x06prefix\x18\x01 \x01(\tR\x06prefix\"A\n" +
	"\fListResponse\x121\n" +
	"\bsessions\x18\x01 \x03(\v2\x15.cm.server.v1.SessionR\bsessions\"\xed\x03\n" +
	"\aSession\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1b\n" +
	"\tshell_pid\x18\x02 \x01(\x05R\bshellPid\x12\x18\n" +
	"\aclients\x18\x03 \x01(\rR\aclients\x12\x10\n" +
	"\x03cwd\x18\x04 \x01(\tR\x03cwd\x12 \n" +
	"\fcwd_is_local\x18\x05 \x01(\bR\n" +
	"cwdIsLocal\x12\x14\n" +
	"\x05title\x18\x06 \x01(\tR\x05title\x12&\n" +
	"\x0fcreated_at_unix\x18\a \x01(\x03R\rcreatedAtUnix\x12\x16\n" +
	"\x06exited\x18\b \x01(\bR\x06exited\x12\x1b\n" +
	"\texit_code\x18\t \x01(\x05R\bexitCode\x120\n" +
	"\x05state\x18\n" +
	" \x01(\x0e2\x1a.cm.server.v1.SessionStateR\x05state\x12\x17\n" +
	"\acwd_uri\x18\v \x01(\tR\x06cwdUri\x12%\n" +
	"\x0ereported_state\x18\x0e \x01(\tR\rreportedState\x12'\n" +
	"\x0freported_detail\x18\x0f \x01(\tR\x0ereportedDetail\x12'\n" +
	"\x0freported_source\x18\x10 \x01(\tR\x0ereportedSource\x12\x12\n" +
	"\x04busy\x18\f \x01(\bR\x04busy\x12\x18\n" +
	"\acommand\x18\r \x01(\tR\acommand\"?\n" +
	"\vKillRequest\x12\x1a\n" +
	"\bsessions\x18\x01 \x03(\tR\bsessions\x12\x14\n" +
	"\x05force\x18\x02 \x01(\bR\x05force\"\xa1\x01\n" +
	"\fKillResponse\x12\x16\n" +
	"\x06killed\x18\x01 \x03(\tR\x06killed\x12>\n" +
	"\x06errors\x18\x02 \x03(\v2&.cm.server.v1.KillResponse.ErrorsEntryR\x06errors\x1a9\n" +
	"\vErrorsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x9b\x01\n" +
	"\vSendRequest\x12\x18\n" +
	"\asession\x18\x01 \x01(\tR\asession\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\x126\n" +
	"\n" +
	"wait_until\x18\x03 \x01(\x0e2\x17.cm.server.v1.WaitStateR\twaitUntil\x12&\n" +
	"\x0fwait_timeout_ms\x18\x04 \x01(\x04R\rwaitTimeoutMs\">\n" +
	"\fSendResponse\x12.\n" +
	"\x04wait\x18\x01 \x01(\v2\x1a.cm.server.v1.WaitResponseR\x04wait\"_\n" +
	"\x0eHistoryRequest\x12\x18\n" +
	"\asession\x18\x01 \x01(\tR\asession\x123\n" +
	"\x06format\x18\x02 \x01(\x0e2\x1b.cm.server.v1.HistoryFormatR\x06format\"%\n" +
	"\x0fHistoryResponse\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\")\n" +
	"\rGetEnvRequest\x12\x18\n" +
	"\asession\x18\x01 \x01(\tR\asession\"\x81\x01\n" +
	"\x0eGetEnvResponse\x127\n" +
	"\x03env\x18\x01 \x03(\v2%.cm.server.v1.GetEnvResponse.EnvEntryR\x03env\x1a6\n" +
	"\bEnvEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01*\x97\x01\n" +
	"\rReportedState\x12\x1e\n" +
	"\x1aREPORTED_STATE_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13REPORTED_STATE_IDLE\x10\x01\x12\x17\n" +
	"\x13REPORTED_STATE_BUSY\x10\x02\x12\x1a\n" +
	"\x16REPORTED_STATE_BLOCKED\x10\x03\x12\x18\n" +
	"\x14REPORTED_STATE_CLEAR\x10\x04*\x80\x01\n" +
	"\tWaitState\x12\x1a\n" +
	"\x16WAIT_STATE_UNSPECIFIED\x10\x00\x12\x13\n" +
	"\x0fWAIT_STATE_IDLE\x10\x01\x12\x13\n" +
	"\x0fWAIT_STATE_BUSY\x10\x02\x12\x15\n" +
	"\x11WAIT_STATE_EXITED\x10\x03\x12\x16\n" +
	"\x12WAIT_STATE_BLOCKED\x10\x04*z\n" +
	"\fSessionState\x12\x1d\n" +
	"\x19SESSION_STATE_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15SESSION_STATE_RUNNING\x10\x01\x12\x18\n" +
	"\x14SESSION_STATE_EXITED\x10\x02\x12\x16\n" +
	"\x12SESSION_STATE_DEAD\x10\x03*_\n" +
	"\rHistoryFormat\x12\x1e\n" +
	"\x1aHISTORY_FORMAT_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11HISTORY_FORMAT_VT\x10\x01\x12\x17\n" +
	"\x13HISTORY_FORMAT_HTML\x10\x022\xb3\x06\n" +
	"\x06Server\x12G\n" +
	"\x06Attach\x12\x1b.cm.server.v1.AttachRequest\x1a\x1c.cm.server.v1.AttachResponse(\x010\x01\x12=\n" +
	"\x04List\x12\x19.cm.server.v1.ListRequest\x1a\x1a.cm.server.v1.ListResponse\x12=\n" +
	"\x04Kill\x12\x19.cm.server.v1.KillRequest\x1a\x1a.cm.server.v1.KillResponse\x12=\n" +
	"\x04Send\x12\x19.cm.server.v1.SendRequest\x1a\x1a.cm.server.v1.SendResponse\x12F\n" +
	"\aHistory\x12\x1c.cm.server.v1.HistoryRequest\x1a\x1d.cm.server.v1.HistoryResponse\x12C\n" +
	"\x06GetEnv\x12\x1b.cm.server.v1.GetEnvRequest\x1a\x1c.cm.server.v1.GetEnvResponse\x12C\n" +
	"\x06Report\x12\x1b.cm.server.v1.ReportRequest\x1a\x1c.cm.server.v1.ReportResponse\x12=\n" +
	"\x04Read\x12\x19.cm.server.v1.ReadRequest\x1a\x1a.cm.server.v1.ReadResponse\x12=\n" +
	"\x04Wait\x12\x19.cm.server.v1.WaitRequest\x1a\x1a.cm.server.v1.WaitResponse\x12C\n" +
	"\x06Doctor\x12\x1b.cm.server.v1.DoctorRequest\x1a\x1c.cm.server.v1.DoctorResponse\x12C\n" +
	"\x06Status\x12\x1b.cm.server.v1.StatusRequest\x1a\x1c.cm.server.v1.StatusResponse\x12I\n" +
	"\bShutdown\x12\x1d.cm.server.v1.ShutdownRequest\x1a\x1e.cm.server.v1.ShutdownResponseB3Z1github.com/chancez/cm/proto/cm/server/v1;serverv1b\x06proto3"

var (
	file_cm_server_v1_server_proto_rawDescOnce sync.Once
	file_cm_server_v1_server_proto_rawDescData []byte
)

func file_cm_server_v1_server_proto_rawDescGZIP() []byte {
	file_cm_server_v1_server_proto_rawDescOnce.Do(func() {
		file_cm_server_v1_server_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_cm_server_v1_server_proto_rawDesc), len(file_cm_server_v1_server_proto_rawDesc)))
	})
	return file_cm_server_v1_server_proto_rawDescData
}

var file_cm_server_v1_server_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_cm_server_v1_server_proto_msgTypes = make([]protoimpl.MessageInfo, 38)
var file_cm_server_v1_server_proto_goTypes = []any{
	(ReportedState)(0),       // 0: cm.server.v1.ReportedState
	(WaitState)(0),           // 1: cm.server.v1.WaitState
	(SessionState)(0),        // 2: cm.server.v1.SessionState
	(HistoryFormat)(0),       // 3: cm.server.v1.HistoryFormat
	(*StatusRequest)(nil),    // 4: cm.server.v1.StatusRequest
	(*StatusResponse)(nil),   // 5: cm.server.v1.StatusResponse
	(*ReportRequest)(nil),    // 6: cm.server.v1.ReportRequest
	(*ReportResponse)(nil),   // 7: cm.server.v1.ReportResponse
	(*ReadRequest)(nil),      // 8: cm.server.v1.ReadRequest
	(*ReadResponse)(nil),     // 9: cm.server.v1.ReadResponse
	(*WaitRequest)(nil),      // 10: cm.server.v1.WaitRequest
	(*WaitResponse)(nil),     // 11: cm.server.v1.WaitResponse
	(*DoctorRequest)(nil),    // 12: cm.server.v1.DoctorRequest
	(*DoctorResponse)(nil),   // 13: cm.server.v1.DoctorResponse
	(*Finding)(nil),          // 14: cm.server.v1.Finding
	(*ShutdownRequest)(nil),  // 15: cm.server.v1.ShutdownRequest
	(*ShutdownResponse)(nil), // 16: cm.server.v1.ShutdownResponse
	(*AttachRequest)(nil),    // 17: cm.server.v1.AttachRequest
	(*Open)(nil),             // 18: cm.server.v1.Open
	(*Input)(nil),            // 19: cm.server.v1.Input
	(*Resize)(nil),           // 20: cm.server.v1.Resize
	(*Detach)(nil),           // 21: cm.server.v1.Detach
	(*AttachResponse)(nil),   // 22: cm.server.v1.AttachResponse
	(*Detached)(nil),         // 23: cm.server.v1.Detached
	(*Metadata)(nil),         // 24: cm.server.v1.Metadata
	(*Opened)(nil),           // 25: cm.server.v1.Opened
	(*Output)(nil),           // 26: cm.server.v1.Output
	(*Exited)(nil),           // 27: cm.server.v1.Exited
	(*ListRequest)(nil),      // 28: cm.server.v1.ListRequest
	(*ListResponse)(nil),     // 29: cm.server.v1.ListResponse
	(*Session)(nil),          // 30: cm.server.v1.Session
	(*KillRequest)(nil),      // 31: cm.server.v1.KillRequest
	(*KillResponse)(nil),     // 32: cm.server.v1.KillResponse
	(*SendRequest)(nil),      // 33: cm.server.v1.SendRequest
	(*SendResponse)(nil),     // 34: cm.server.v1.SendResponse
	(*HistoryRequest)(nil),   // 35: cm.server.v1.HistoryRequest
	(*HistoryResponse)(nil),  // 36: cm.server.v1.HistoryResponse
	(*GetEnvRequest)(nil),    // 37: cm.server.v1.GetEnvRequest
	(*GetEnvResponse)(nil),   // 38: cm.server.v1.GetEnvResponse
	nil,                      // 39: cm.server.v1.Open.ClientEnvEntry
	nil,                      // 40: cm.server.v1.KillResponse.ErrorsEntry
	nil,                      // 41: cm.server.v1.GetEnvResponse.EnvEntry
}
var file_cm_server_v1_server_proto_depIdxs = []int32{
	0,  // 0: cm.server.v1.ReportRequest.state:type_name -> cm.server.v1.ReportedState
	1,  // 1: cm.server.v1.WaitRequest.until:type_name -> cm.server.v1.WaitState
	2,  // 2: cm.server.v1.WaitResponse.state:type_name -> cm.server.v1.SessionState
	14, // 3: cm.server.v1.DoctorResponse.findings:type_name -> cm.server.v1.Finding
	18, // 4: cm.server.v1.AttachRequest.open:type_name -> cm.server.v1.Open
	19, // 5: cm.server.v1.AttachRequest.input:type_name -> cm.server.v1.Input
	20, // 6: cm.server.v1.AttachRequest.resize:type_name -> cm.server.v1.Resize
	21, // 7: cm.server.v1.AttachRequest.detach:type_name -> cm.server.v1.Detach
	39, // 8: cm.server.v1.Open.client_env:type_name -> cm.server.v1.Open.ClientEnvEntry
	25, // 9: cm.server.v1.AttachResponse.opened:type_name -> cm.server.v1.Opened
	26, // 10: cm.server.v1.AttachResponse.output:type_name -> cm.server.v1.Output
	27, // 11: cm.server.v1.AttachResponse.exited:type_name -> cm.server.v1.Exited
	24, // 12: cm.server.v1.AttachResponse.metadata:type_name -> cm.server.v1.Metadata
	23, // 13: cm.server.v1.AttachResponse.detached:type_name -> cm.server.v1.Detached
	30, // 14: cm.server.v1.ListResponse.sessions:type_name -> cm.server.v1.Session
	2,  // 15: cm.server.v1.Session.state:type_name -> cm.server.v1.SessionState
	40, // 16: cm.server.v1.KillResponse.errors:type_name -> cm.server.v1.KillResponse.ErrorsEntry
	1,  // 17: cm.server.v1.SendRequest.wait_until:type_name -> cm.server.v1.WaitState
	11, // 18: cm.server.v1.SendResponse.wait:type_name -> cm.server.v1.WaitResponse
	3,  // 19: cm.server.v1.HistoryRequest.format:type_name -> cm.server.v1.HistoryFormat
	41, // 20: cm.server.v1.GetEnvResponse.env:type_name -> cm.server.v1.GetEnvResponse.EnvEntry
	17, // 21: cm.server.v1.Server.Attach:input_type -> cm.server.v1.AttachRequest
	28, // 22: cm.server.v1.Server.List:input_type -> cm.server.v1.ListRequest
	31, // 23: cm.server.v1.Server.Kill:input_type -> cm.server.v1.KillRequest
	33, // 24: cm.server.v1.Server.Send:input_type -> cm.server.v1.SendRequest
	35, // 25: cm.server.v1.Server.History:input_type -> cm.server.v1.HistoryRequest
	37, // 26: cm.server.v1.Server.GetEnv:input_type -> cm.server.v1.GetEnvRequest
	6,  // 27: cm.server.v1.Server.Report:input_type -> cm.server.v1.ReportRequest
	8,  // 28: cm.server.v1.Server.Read:input_type -> cm.server.v1.ReadRequest
	10, // 29: cm.server.v1.Server.Wait:input_type -> cm.server.v1.WaitRequest
	12, // 30: cm.server.v1.Server.Doctor:input_type -> cm.server.v1.DoctorRequest
	4,  // 31: cm.server.v1.Server.Status:input_type -> cm.server.v1.StatusRequest
	15, // 32: cm.server.v1.Server.Shutdown:input_type -> cm.server.v1.ShutdownRequest
	22, // 33: cm.server.v1.Server.Attach:output_type -> cm.server.v1.AttachResponse
	29, // 34: cm.server.v1.Server.List:output_type -> cm.server.v1.ListResponse
	32, // 35: cm.server.v1.Server.Kill:output_type -> cm.server.v1.KillResponse
	34, // 36: cm.server.v1.Server.Send:output_type -> cm.server.v1.SendResponse
	36, // 37: cm.server.v1.Server.History:output_type -> cm.server.v1.HistoryResponse
	38, // 38: cm.server.v1.Server.GetEnv:output_type -> cm.server.v1.GetEnvResponse
	7,  // 39: cm.server.v1.Server.Report:output_type -> cm.server.v1.ReportResponse
	9,  // 40: cm.server.v1.Server.Read:output_type -> cm.server.v1.ReadResponse
	11, // 41: cm.server.v1.Server.Wait:output_type -> cm.server.v1.WaitResponse
	13, // 42: cm.server.v1.Server.Doctor:output_type -> cm.server.v1.DoctorResponse
	5,  // 43: cm.server.v1.Server.Status:output_type -> cm.server.v1.StatusResponse
	16, // 44: cm.server.v1.Server.Shutdown:output_type -> cm.server.v1.ShutdownResponse
	33, // [33:45] is the sub-list for method output_type
	21, // [21:33] is the sub-list for method input_type
	21, // [21:21] is the sub-list for extension type_name
	21, // [21:21] is the sub-list for extension extendee
	0,  // [0:21] is the sub-list for field type_name
}

func init() { file_cm_server_v1_server_proto_init() }
func file_cm_server_v1_server_proto_init() {
	if File_cm_server_v1_server_proto != nil {
		return
	}
	file_cm_server_v1_server_proto_msgTypes[13].OneofWrappers = []any{
		(*AttachRequest_Open)(nil),
		(*AttachRequest_Input)(nil),
		(*AttachRequest_Resize)(nil),
		(*AttachRequest_Detach)(nil),
	}
	file_cm_server_v1_server_proto_msgTypes[14].OneofWrappers = []any{}
	file_cm_server_v1_server_proto_msgTypes[18].OneofWrappers = []any{
		(*AttachResponse_Opened)(nil),
		(*AttachResponse_Output)(nil),
		(*AttachResponse_Exited)(nil),
		(*AttachResponse_Metadata)(nil),
		(*AttachResponse_Detached)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cm_server_v1_server_proto_rawDesc), len(file_cm_server_v1_server_proto_rawDesc)),
			NumEnums:      4,
			NumMessages:   38,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_cm_server_v1_server_proto_goTypes,
		DependencyIndexes: file_cm_server_v1_server_proto_depIdxs,
		EnumInfos:         file_cm_server_v1_server_proto_enumTypes,
		MessageInfos:      file_cm_server_v1_server_proto_msgTypes,
	}.Build()
	File_cm_server_v1_server_proto = out.File
	file_cm_server_v1_server_proto_goTypes = nil
	file_cm_server_v1_server_proto_depIdxs = nil
}
