// Code generated by protoc-gen-go-ttrpc. DO NOT EDIT.
// source: cm/shim/v1/shim.proto
package shimv1

import (
	context "context"
	ttrpc "github.com/containerd/ttrpc"
)

type ShimService interface {
	State(context.Context, *StateRequest) (*StateResponse, error)
	Subscribe(context.Context, *SubscribeRequest, Shim_SubscribeServer) error
	Write(context.Context, *WriteRequest) (*WriteResponse, error)
	Resize(context.Context, *ResizeRequest) (*ResizeResponse, error)
	Signal(context.Context, *SignalRequest) (*SignalResponse, error)
	Shutdown(context.Context, *ShutdownRequest) (*ShutdownResponse, error)
}

type Shim_SubscribeServer interface {
	Send(*Output) error
	ttrpc.StreamServer
}

type shimSubscribeServer struct {
	ttrpc.StreamServer
}

func (x *shimSubscribeServer) Send(m *Output) error {
	return x.StreamServer.SendMsg(m)
}

func RegisterShimService(srv *ttrpc.Server, svc ShimService) {
	srv.RegisterService("cm.shim.v1.Shim", &ttrpc.ServiceDesc{
		Methods: map[string]ttrpc.Method{
			"State": func(ctx context.Context, unmarshal func(interface{}) error) (interface{}, error) {
				var req StateRequest
				if err := unmarshal(&req); err != nil {
					return nil, err
				}
				return svc.State(ctx, &req)
			},
			"Write": func(ctx context.Context, unmarshal func(interface{}) error) (interface{}, error) {
				var req WriteRequest
				if err := unmarshal(&req); err != nil {
					return nil, err
				}
				return svc.Write(ctx, &req)
			},
			"Resize": func(ctx context.Context, unmarshal func(interface{}) error) (interface{}, error) {
				var req ResizeRequest
				if err := unmarshal(&req); err != nil {
					return nil, err
				}
				return svc.Resize(ctx, &req)
			},
			"Signal": func(ctx context.Context, unmarshal func(interface{}) error) (interface{}, error) {
				var req SignalRequest
				if err := unmarshal(&req); err != nil {
					return nil, err
				}
				return svc.Signal(ctx, &req)
			},
			"Shutdown": func(ctx context.Context, unmarshal func(interface{}) error) (interface{}, error) {
				var req ShutdownRequest
				if err := unmarshal(&req); err != nil {
					return nil, err
				}
				return svc.Shutdown(ctx, &req)
			},
		},
		Streams: map[string]ttrpc.Stream{
			"Subscribe": {
				Handler: func(ctx context.Context, stream ttrpc.StreamServer) (interface{}, error) {
					m := new(SubscribeRequest)
					if err := stream.RecvMsg(m); err != nil {
						return nil, err
					}
					return nil, svc.Subscribe(ctx, m, &shimSubscribeServer{stream})
				},
				StreamingClient: false,
				StreamingServer: true,
			},
		},
	})
}

type ShimClient interface {
	State(context.Context, *StateRequest) (*StateResponse, error)
	Subscribe(context.Context, *SubscribeRequest) (Shim_SubscribeClient, error)
	Write(context.Context, *WriteRequest) (*WriteResponse, error)
	Resize(context.Context, *ResizeRequest) (*ResizeResponse, error)
	Signal(context.Context, *SignalRequest) (*SignalResponse, error)
	Shutdown(context.Context, *ShutdownRequest) (*ShutdownResponse, error)
}

type shimClient struct {
	client *ttrpc.Client
}

func NewShimClient(client *ttrpc.Client) ShimClient {
	return &shimClient{
		client: client,
	}
}

func (c *shimClient) State(ctx context.Context, req *StateRequest) (*StateResponse, error) {
	var resp StateResponse
	if err := c.client.Call(ctx, "cm.shim.v1.Shim", "State", req, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}

func (c *shimClient) Subscribe(ctx context.Context, req *SubscribeRequest) (Shim_SubscribeClient, error) {
	stream, err := c.client.NewStream(ctx, &ttrpc.StreamDesc{
		StreamingClient: false,
		StreamingServer: true,
	}, "cm.shim.v1.Shim", "Subscribe", req)
	if err != nil {
		return nil, err
	}
	x := &shimSubscribeClient{stream}
	return x, nil
}

type Shim_SubscribeClient interface {
	Recv() (*Output, error)
	ttrpc.ClientStream
}

type shimSubscribeClient struct {
	ttrpc.ClientStream
}

func (x *shimSubscribeClient) Recv() (*Output, error) {
	m := new(Output)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *shimClient) Write(ctx context.Context, req *WriteRequest) (*WriteResponse, error) {
	var resp WriteResponse
	if err := c.client.Call(ctx, "cm.shim.v1.Shim", "Write", req, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}

func (c *shimClient) Resize(ctx context.Context, req *ResizeRequest) (*ResizeResponse, error) {
	var resp ResizeResponse
	if err := c.client.Call(ctx, "cm.shim.v1.Shim", "Resize", req, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}

func (c *shimClient) Signal(ctx context.Context, req *SignalRequest) (*SignalResponse, error) {
	var resp SignalResponse
	if err := c.client.Call(ctx, "cm.shim.v1.Shim", "Signal", req, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}

func (c *shimClient) Shutdown(ctx context.Context, req *ShutdownRequest) (*ShutdownResponse, error) {
	var resp ShutdownResponse
	if err := c.client.Call(ctx, "cm.shim.v1.Shim", "Shutdown", req, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}
