// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: cm/shim/v1/shim.proto

// Package cm.shim.v1 is the interface between the server and one session's shim.
//
// This API is frozen in a way the client-facing API is not. Upgrading the cm binary
// does not upgrade shims that are already running: they hold the pty for a live shell,
// which is the entire reason the layer exists. A new server therefore routinely talks to
// an older shim, and an older server can meet a newer shim after a downgrade.
//
// The rules that follow from that:
//   - Never remove or renumber a field, and never change a field's type or meaning.
//   - Add optional fields only, and treat their absence as "the peer predates this".
//   - Never make a new RPC load-bearing for an existing feature. A server must degrade
//     gracefully when an older shim returns "unimplemented".
//
// Keeping this surface small is the point: the shim owns the pty and an append-only log
// of output, and knows nothing about terminal emulation, scrollback, or session policy.

package shimv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StateRequest) Reset() {
	*x = StateRequest{}
	mi := &file_cm_shim_v1_shim_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StateRequest) ProtoMessage() {}

func (x *StateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cm_shim_v1_shim_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StateRequest.ProtoReflect.Descriptor instead.
func (*StateRequest) Descriptor() ([]byte, []int) {
	return file_cm_shim_v1_shim_proto_rawDescGZIP(), []int{0}
}

type StateResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Session name this shim serves.
	Session string `protobuf:"bytes,1,opt,name=session,proto3" json:"session,omitempty"`
	// Process id of the shim itself.
	ShimPid int32 `protobuf:"varint,2,opt,name=shim_pid,json=shimPid,proto3" json:"shim_pid,omitempty"`
	// Process id of the shell. Zero once it has exited.
	ShellPid int32 `protobuf:"varint,3,opt,name=shell_pid,json=shellPid,proto3" json:"shell_pid,omitempty"`
	// Sequence number one past the last byte appended to the log. A subscriber that has
	// seen up to this value is fully caught up.
	NextSeq uint64 `protobuf:"varint,4,opt,name=next_seq,json=nextSeq,proto3" json:"next_seq,omitempty"`
	// Lowest sequence number still retained. Output before this was truncated, so a
	// subscriber asking for less than this cannot be served exactly and must be told.
	OldestSeq uint64 `protobuf:"varint,5,opt,name=oldest_seq,json=oldestSeq,proto3" json:"oldest_seq,omitempty"`
	// Whether the shell has exited.
	Exited bool `protobuf:"varint,6,opt,name=exited,proto3" json:"exited,omitempty"`
	// Exit status, meaningful only when exited is true.
	ExitCode int32 `protobuf:"varint,7,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	// Window size currently set on the pty.
	Rows          uint32 `protobuf:"varint,8,opt,name=rows,proto3" json:"rows,omitempty"`
	Cols          uint32 `protobuf:"varint,9,opt,name=cols,proto3" json:"cols,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StateResponse) Reset() {
	*x = StateResponse{}
	mi := &file_cm_shim_v1_shim_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StateResponse) ProtoMessage() {}

func (x *StateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cm_shim_v1_shim_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StateResponse.ProtoReflect.Descriptor instead.
func (*StateResponse) Descriptor() ([]byte, []int) {
	return file_cm_shim_v1_shim_proto_rawDescGZIP(), []int{1}
}

func (x *StateResponse) GetSession() string {
	if x != nil {
		return x.Session
	}
	return ""
}

func (x *StateResponse) GetShimPid() int32 {
	if x != nil {
		return x.ShimPid
	}
	return 0
}

func (x *StateResponse) GetShellPid() int32 {
	if x != nil {
		return x.ShellPid
	}
	return 0
}

func (x *StateResponse) GetNextSeq() uint64 {
	if x != nil {
		return x.NextSeq
	}
	return 0
}

func (x *StateResponse) GetOldestSeq() uint64 {
	if x != nil {
		return x.OldestSeq
	}
	return 0
}

func (x *StateResponse) GetExited() bool {
	if x != nil {
		return x.Exited
	}
	return false
}

func (x *StateResponse) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

func (x *StateResponse) GetRows() uint32 {
	if x != nil {
		return x.Rows
	}
	return 0
}

func (x *StateResponse) GetCols() uint32 {
	if x != nil {
		return x.Cols
	}
	return 0
}

type SubscribeRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// First sequence number wanted. Zero means "from the beginning of what is retained".
	FromSeq       uint64 `protobuf:"varint,1,opt,name=from_seq,json=fromSeq,proto3" json:"from_seq,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeRequest) Reset() {
	*x = SubscribeRequest{}
	mi := &file_cm_shim_v1_shim_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeRequest) ProtoMessage() {}

func (x *SubscribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cm_shim_v1_shim_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeRequest.ProtoReflect.Descriptor instead.
func (*SubscribeRequest) Descriptor() ([]byte, []int) {
	return file_cm_shim_v1_shim_proto_rawDescGZIP(), []int{2}
}

func (x *SubscribeRequest) GetFromSeq() uint64 {
	if x != nil {
		return x.FromSeq
	}
	return 0
}

// Output carries a run of pty output bytes.
type Output struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Sequence number of the first byte in data.
	Seq  uint64 `protobuf:"varint,1,opt,name=seq,proto3" json:"seq,omitempty"`
	Data []byte `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	// Set when the requested from_seq had already been truncated. The bytes that follow
	// start at the oldest retained sequence instead, so the receiver knows its terminal
	// state has a hole and must resynchronize rather than assume continuity.
	Gap           bool `protobuf:"varint,3,opt,name=gap,proto3" json:"gap,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Output) Reset() {
	*x = Output{}
	mi := &file_cm_shim_v1_shim_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Output) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Output) ProtoMessage() {}

func (x *Output) ProtoReflect() protoreflect.Message {
	mi := &file_cm_shim_v1_shim_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Output.ProtoReflect.Descriptor instead.
func (*Output) Descriptor() ([]byte, []int) {
	return file_cm_shim_v1_shim_proto_rawDescGZIP(), []int{3}
}

func (x *Output) GetSeq() uint64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *Output) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *Output) GetGap() bool {
	if x != nil {
		return x.Gap
	}
	return false
}

type WriteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteRequest) Reset() {
	*x = WriteRequest{}
	mi := &file_cm_shim_v1_shim_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteRequest) ProtoMessage() {}

func (x *WriteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cm_shim_v1_shim_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteRequest.ProtoReflect.Descriptor instead.
func (*WriteRequest) Descriptor() ([]byte, []int) {
	return file_cm_shim_v1_shim_proto_rawDescGZIP(), []int{4}
}

func (x *WriteRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type WriteResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Bytes accepted. May be short: the shim bounds its pty write buffer so a wedged
	// shell cannot make it grow without limit.
	Written       uint64 `protobuf:"varint,1,opt,name=written,proto3" json:"written,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteResponse) Reset() {
	*x = WriteResponse{}
	mi := &file_cm_shim_v1_shim_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteResponse) ProtoMessage() {}

func (x *WriteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cm_shim_v1_shim_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteResponse.ProtoReflect.Descriptor instead.
func (*WriteResponse) Descriptor() ([]byte, []int) {
	return file_cm_shim_v1_shim_proto_rawDescGZIP(), []int{5}
}

func (x *WriteResponse) GetWritten() uint64 {
	if x != nil {
		return x.Written
	}
	return 0
}

type ResizeRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Rows  uint32                 `protobuf:"varint,1,opt,name=rows,proto3" json:"rows,omitempty"`
	Cols  uint32                 `protobuf:"varint,2,opt,name=cols,proto3" json:"cols,omitempty"`
	// Pixel dimensions, for programs that ask. Zero when unknown.
	XPixel uint32 `protobuf:"varint,3,opt,name=x_pixel,json=xPixel,proto3" json:"x_pixel,omitempty"`
	YPixel uint32 `protobuf:"varint,4,opt,name=y_pixel,json=yPixel,proto3" json:"y_pixel,omitempty"`
	// Make the shell see a window-size change even when the size is unchanged.
	//
	// The kernel raises SIGWINCH only when the size actually differs, so a client reattaching at
	// the size the session already has gets nothing, and a program that repaints only on SIGWINCH
	// keeps drawing against a screen that is now a replayed snapshot.
	//
	// Optional so an older shim that does not understand it simply resizes as before, which is the
	// current behavior rather than a failure.
	ForceSignal   bool `protobuf:"varint,5,opt,name=force_signal,json=forceSignal,proto3" json:"force_signal,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResizeRequest) Reset() {
	*x = ResizeRequest{}
	mi := &file_cm_shim_v1_shim_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResizeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResizeRequest) ProtoMessage() {}

func (x *ResizeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cm_shim_v1_shim_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResizeRequest.ProtoReflect.Descriptor instead.
func (*ResizeRequest) Descriptor() ([]byte, []int) {
	return file_cm_shim_v1_shim_proto_rawDescGZIP(), []int{6}
}

func (x *ResizeRequest) GetRows() uint32 {
	if x != nil {
		return x.Rows
	}
	return 0
}

func (x *ResizeRequest) GetCols() uint32 {
	if x != nil {
		return x.Cols
	}
	return 0
}

func (x *ResizeRequest) GetXPixel() uint32 {
	if x != nil {
		return x.XPixel
	}
	return 0
}

func (x *ResizeRequest) GetYPixel() uint32 {
	if x != nil {
		return x.YPixel
	}
	return 0
}

func (x *ResizeRequest) GetForceSignal() bool {
	if x != nil {
		return x.ForceSignal
	}
	return false
}

type ResizeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResizeResponse) Reset() {
	*x = ResizeResponse{}
	mi := &file_cm_shim_v1_shim_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResizeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResizeResponse) ProtoMessage() {}

func (x *ResizeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cm_shim_v1_shim_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResizeResponse.ProtoReflect.Descriptor instead.
func (*ResizeResponse) Descriptor() ([]byte, []int) {
	return file_cm_shim_v1_shim_proto_rawDescGZIP(), []int{7}
}

type SignalRequest struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Signal int32                  `protobuf:"varint,1,opt,name=signal,proto3" json:"signal,omitempty"`
	// Send to the shell's process group rather than the single process, so job control
	// reaches children too.
	ProcessGroup  bool `protobuf:"varint,2,opt,name=process_group,json=processGroup,proto3" json:"process_group,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignalRequest) Reset() {
	*x = SignalRequest{}
	mi := &file_cm_shim_v1_shim_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignalRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignalRequest) ProtoMessage() {}

func (x *SignalRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cm_shim_v1_shim_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignalRequest.ProtoReflect.Descriptor instead.
func (*SignalRequest) Descriptor() ([]byte, []int) {
	return file_cm_shim_v1_shim_proto_rawDescGZIP(), []int{8}
}

func (x *SignalRequest) GetSignal() int32 {
	if x != nil {
		return x.Signal
	}
	return 0
}

func (x *SignalRequest) GetProcessGroup() bool {
	if x != nil {
		return x.ProcessGroup
	}
	return false
}

type SignalResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignalResponse) Reset() {
	*x = SignalResponse{}
	mi := &file_cm_shim_v1_shim_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignalResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignalResponse) ProtoMessage() {}

func (x *SignalResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cm_shim_v1_shim_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignalResponse.ProtoReflect.Descriptor instead.
func (*SignalResponse) Descriptor() ([]byte, []int) {
	return file_cm_shim_v1_shim_proto_rawDescGZIP(), []int{9}
}

type ShutdownRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Skip the graceful SIGHUP-then-wait and kill immediately.
	Force bool `protobuf:"varint,1,opt,name=force,proto3" json:"force,omitempty"`
	// Signal to end the session with, overriding what force selects.
	//
	// Zero means "not specified", which is what an older server sends and what keeps this additive: a
	// shim reading zero falls back to force, so the two fields cannot disagree about a request neither
	// side has an opinion on.
	//
	// The reverse direction matters more and cannot be fixed here. An older shim ignores this field
	// entirely and honors force alone, so a newer server asking for a specific signal gets SIGHUP or
	// SIGKILL from it instead. That is a degradation rather than a failure, and the server logs it
	// rather than pretending the signal was delivered.
	Signal        int32 `protobuf:"varint,2,opt,name=signal,proto3" json:"signal,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShutdownRequest) Reset() {
	*x = ShutdownRequest{}
	mi := &file_cm_shim_v1_shim_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShutdownRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShutdownRequest) ProtoMessage() {}

func (x *ShutdownRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cm_shim_v1_shim_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShutdownRequest.ProtoReflect.Descriptor instead.
func (*ShutdownRequest) Descriptor() ([]byte, []int) {
	return file_cm_shim_v1_shim_proto_rawDescGZIP(), []int{10}
}

func (x *ShutdownRequest) GetForce() bool {
	if x != nil {
		return x.Force
	}
	return false
}

func (x *ShutdownRequest) GetSignal() int32 {
	if x != nil {
		return x.Signal
	}
	return 0
}

type ShutdownResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShutdownResponse) Reset() {
	*x = ShutdownResponse{}
	mi := &file_cm_shim_v1_shim_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShutdownResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShutdownResponse) ProtoMessage() {}

func (x *ShutdownResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cm_shim_v1_shim_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShutdownResponse.ProtoReflect.Descriptor instead.
func (*ShutdownResponse) Descriptor() ([]byte, []int) {
	return file_cm_shim_v1_shim_proto_rawDescGZIP(), []int{11}
}

var File_cm_shim_v1_shim_proto protoreflect.FileDescriptor

const file_cm_shim_v1_shim_proto_rawDesc = "" +
	"\n" +
	"\x15cm/shim/v1/shim.proto\x12\n" +
	"cm.shim.v1\"\x0e\n" +
	"\fStateRequest\"\xf8\x01\n" +
	"\rStateResponse\x12\x18\n" +
	"\asession\x18\x01 \x01(\tR\asession\x12\x19\n" +
	"\bshim_pid\x18\x02 \x01(\x05R\ashimPid\x12\x1b\n" +
	"\tshell_pid\x18\x03 \x01(\x05R\bshellPid\x12\x19\n" +
	"\bnext_seq\x18\x04 \x01(\x04R\anextSeq\x12\x1d\n" +
	"\n" +
	"oldest_seq\x18\x05 \x01(\x04R\toldestSeq\x12\x16\n" +
	"\x06exited\x18\x06 \x01(\bR\x06exited\x12\x1b\n" +
	"\texit_code\x18\a \x01(\x05R\bexitCode\x12\x12\n" +
	"\x04rows\x18\b \x01(\rR\x04rows\x12\x12\n" +
	"\x04cols\x18\t \x01(\rR\x04cols\"-\n" +
	"\x10SubscribeRequest\x12\x19\n" +
	"\bfrom_seq\x18\x01 \x01(\x04R\afromSeq\"@\n" +
	"\x06Output\x12\x10\n" +
	"\x03seq\x18\x01 \x01(\x04R\x03seq\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\x12\x10\n" +
	"\x03gap\x18\x03 \x01(\bR\x03gap\"\"\n" +
	"\fWriteRequest\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\")\n" +
	"\rWriteResponse\x12\x18\n" +
	"\awritten\x18\x01 \x01(\x04R\awritten\"\x8c\x01\n" +
	"\rResizeRequest\x12\x12\n" +
	"\x04rows\x18\x01 \x01(\rR\x04rows\x12\x12\n" +
	"\x04cols\x18\x02 \x01(\rR\x04cols\x12\x17\n" +
	"\ax_pixel\x18\x03 \x01(\rR\x06xPixel\x12\x17\n" +
	"\ay_pixel\x18\x04 \x01(\rR\x06yPixel\x12!\n" +
	"\fforce_signal\x18\x05 \x01(\bR\vforceSignal\"\x10\n" +
	"\x0eResizeResponse\"L\n" +
	"\rSignalRequest\x12\x16\n" +
	"\x06signal\x18\x01 \x01(\x05R\x06signal\x12#\n" +
	"\rprocess_group\x18\x02 \x01(\bR\fprocessGroup\"\x10\n" +
	"\x0eSignalResponse\"?\n" +
	"\x0fShutdownRequest\x12\x14\n" +
	"\x05force\x18\x01 \x01(\bR\x05force\x12\x16\n" +
	"\x06signal\x18\x02 \x01(\x05R\x06signal\"\x12\n" +
	"\x10ShutdownResponse2\x8c\x03\n" +
	"\x04Shim\x12<\n" +
	"\x05State\x12\x18.cm.shim.v1.StateRequest\x1a\x19.cm.shim.v1.StateResponse\x12?\n" +
	"\tSubscribe\x12\x1c.cm.shim.v1.SubscribeRequest\x1a\x12.cm.shim.v1.Output0\x01\x12<\n" +
	"\x05Write\x12\x18.cm.shim.v1.WriteRequest\x1a\x19.cm.shim.v1.WriteResponse\x12?\n" +
	"\x06Resize\x12\x19.cm.shim.v1.ResizeRequest\x1a\x1a.cm.shim.v1.ResizeResponse\x12?\n" +
	"\x06Signal\x12\x19.cm.shim.v1.SignalRequest\x1a\x1a.cm.shim.v1.SignalResponse\x12E\n" +
	"\bShutdown\x12\x1b.cm.shim.v1.ShutdownRequest\x1a\x1c.cm.shim.v1.ShutdownResponseB/Z-github.com/chancez/cm/proto/cm/shim/v1;shimv1b\x06proto3"

var (
	file_cm_shim_v1_shim_proto_rawDescOnce sync.Once
	file_cm_shim_v1_shim_proto_rawDescData []byte
)

func file_cm_shim_v1_shim_proto_rawDescGZIP() []byte {
	file_cm_shim_v1_shim_proto_rawDescOnce.Do(func() {
		file_cm_shim_v1_shim_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_cm_shim_v1_shim_proto_rawDesc), len(file_cm_shim_v1_shim_proto_rawDesc)))
	})
	return file_cm_shim_v1_shim_proto_rawDescData
}

var file_cm_shim_v1_shim_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_cm_shim_v1_shim_proto_goTypes = []any{
	(*StateRequest)(nil),     // 0: cm.shim.v1.StateRequest
	(*StateResponse)(nil),    // 1: cm.shim.v1.StateResponse
	(*SubscribeRequest)(nil), // 2: cm.shim.v1.SubscribeRequest
	(*Output)(nil),           // 3: cm.shim.v1.Output
	(*WriteRequest)(nil),     // 4: cm.shim.v1.WriteRequest
	(*WriteResponse)(nil),    // 5: cm.shim.v1.WriteResponse
	(*ResizeRequest)(nil),    // 6: cm.shim.v1.ResizeRequest
	(*ResizeResponse)(nil),   // 7: cm.shim.v1.ResizeResponse
	(*SignalRequest)(nil),    // 8: cm.shim.v1.SignalRequest
	(*SignalResponse)(nil),   // 9: cm.shim.v1.SignalResponse
	(*ShutdownRequest)(nil),  // 10: cm.shim.v1.ShutdownRequest
	(*ShutdownResponse)(nil), // 11: cm.shim.v1.ShutdownResponse
}
var file_cm_shim_v1_shim_proto_depIdxs = []int32{
	0,  // 0: cm.shim.v1.Shim.State:input_type -> cm.shim.v1.StateRequest
	2,  // 1: cm.shim.v1.Shim.Subscribe:input_type -> cm.shim.v1.SubscribeRequest
	4,  // 2: cm.shim.v1.Shim.Write:input_type -> cm.shim.v1.WriteRequest
	6,  // 3: cm.shim.v1.Shim.Resize:input_type -> cm.shim.v1.ResizeRequest
	8,  // 4: cm.shim.v1.Shim.Signal:input_type -> cm.shim.v1.SignalRequest
	10, // 5: cm.shim.v1.Shim.Shutdown:input_type -> cm.shim.v1.ShutdownRequest
	1,  // 6: cm.shim.v1.Shim.State:output_type -> cm.shim.v1.StateResponse
	3,  // 7: cm.shim.v1.Shim.Subscribe:output_type -> cm.shim.v1.Output
	5,  // 8: cm.shim.v1.Shim.Write:output_type -> cm.shim.v1.WriteResponse
	7,  // 9: cm.shim.v1.Shim.Resize:output_type -> cm.shim.v1.ResizeResponse
	9,  // 10: cm.shim.v1.Shim.Signal:output_type -> cm.shim.v1.SignalResponse
	11, // 11: cm.shim.v1.Shim.Shutdown:output_type -> cm.shim.v1.ShutdownResponse
	6,  // [6:12] is the sub-list for method output_type
	0,  // [0:6] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_cm_shim_v1_shim_proto_init() }
func file_cm_shim_v1_shim_proto_init() {
	if File_cm_shim_v1_shim_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cm_shim_v1_shim_proto_rawDesc), len(file_cm_shim_v1_shim_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_cm_shim_v1_shim_proto_goTypes,
		DependencyIndexes: file_cm_shim_v1_shim_proto_depIdxs,
		MessageInfos:      file_cm_shim_v1_shim_proto_msgTypes,
	}.Build()
	File_cm_shim_v1_shim_proto = out.File
	file_cm_shim_v1_shim_proto_goTypes = nil
	file_cm_shim_v1_shim_proto_depIdxs = nil
}
