package input

import (
	"bytes"
	"testing"
)

// The modes a program that quit had set, and the modes left behind once it has.
var (
	codexRunning = TerminalModes{KittyKeyboard: true, FocusReports: true}
	codexGone    = TerminalModes{}
)

func TestIsStaleEvent(t *testing.T) {
	for _, tc := range []struct {
		name  string
		seq   string
		modes TerminalModes
		want  bool
	}{
		// The reported bug: codex quit, and the release of the key that quit it arrives afterwards.
		{"ctrl-d release, program gone", "\x1b[100;5:3u", codexGone, true},
		{"focus out, program gone", "\x1b[O", codexGone, true},
		{"focus in, program gone", "\x1b[I", codexGone, true},

		// While the program is running these are exactly what it asked for.
		{"ctrl-d release, program running", "\x1b[100;5:3u", codexRunning, false},
		{"focus out, program running", "\x1b[O", codexRunning, false},

		// The modes are independent, so one being off must not drop the other's events.
		{"release when only focus is off", "\x1b[100;5:3u",
			TerminalModes{KittyKeyboard: true}, false},
		{"focus out when only the protocol is off", "\x1b[O",
			TerminalModes{FocusReports: true}, false},

		// A press is never stale, whatever the modes say. Dropping one would make a session ignore
		// the keyboard, which is the failure this deliberately refuses to risk.
		{"press with an explicit event type", "\x1b[100;5:1u", codexGone, false},
		{"press with no event type", "\x1b[100;5u", codexGone, false},
		{"repeat", "\x1b[100;5:2u", codexGone, false},
		{"plain key", "\x1b[97u", codexGone, false},

		// The flags reply ends in 'u' too and belongs to the query proxy.
		{"kitty flags reply", "\x1b[?7u", codexGone, false},
		{"kitty flags reply, zero", "\x1b[?0u", codexGone, false},

		// Other things ending in these finals are not events.
		{"parameterized I is not focus", "\x1b[2I", codexGone, false},
		{"parameterized O is not focus", "\x1b[2O", codexGone, false},

		// Not this mechanism's business at all.
		{"arrow key", "\x1b[A", codexGone, false},
		{"mouse report", "\x1b[<0;10;5M", codexGone, false},
		{"cursor position report", "\x1b[10;20R", codexGone, false},
		{"modifyOtherKeys key", "\x1b[27;5;92~", codexGone, false},
		{"incomplete", "\x1b[100;5:3", codexGone, false},
		{"lone escape", "\x1b", codexGone, false},
		{"printable", "x", codexGone, false},
		{"empty", "", codexGone, false},
	} {
		t.Run(tc.name, func(t *testing.T) {
			if got := IsStaleEvent([]byte(tc.seq), tc.modes); got != tc.want {
				t.Errorf("IsStaleEvent(%q, %+v) = %v, want %v", tc.seq, tc.modes, got, tc.want)
			}
		})
	}
}

func TestDropStaleEvents(t *testing.T) {
	for _, tc := range []struct {
		name  string
		in    string
		modes TerminalModes
		want  string
	}{
		{
			// The reported chunk. Everything in it was generated by modes the exited program set.
			name:  "release and focus report together",
			in:    "\x1b[100;5:3u\x1b[O",
			modes: codexGone,
			want:  "",
		},
		{
			// The case that decides whether this is safe: a stale event arriving in the same read as
			// something the user typed. Dropping the whole chunk would swallow the keystroke.
			name:  "stale event next to real typing",
			in:    "\x1b[100;5:3u" + "ls -la\r",
			modes: codexGone,
			want:  "ls -la\r",
		},
		{
			name:  "typing before and after",
			in:    "ab\x1b[Ocd",
			modes: codexGone,
			want:  "abcd",
		},
		{
			name:  "nothing stale is returned unchanged",
			in:    "\x1b[A\x1b[Bhello\r",
			modes: codexGone,
			want:  "\x1b[A\x1b[Bhello\r",
		},
		{
			name:  "program running, nothing dropped",
			in:    "\x1b[100;5:3u\x1b[O",
			modes: codexRunning,
			want:  "\x1b[100;5:3u\x1b[O",
		},
		{
			// A press must survive even sandwiched between stale releases.
			name:  "press between releases",
			in:    "\x1b[100;5:3u\x1b[97;1:1u\x1b[100;5:3u",
			modes: codexGone,
			want:  "\x1b[97;1:1u",
		},
		{
			// A lone ESC must not hide what follows it: skipping the whole tail on an unparseable
			// sequence would leave a stale event in place.
			name:  "lone escape then a stale event",
			in:    "\x1b\x1b[O",
			modes: codexGone,
			want:  "\x1b",
		},
		{
			name:  "empty",
			in:    "",
			modes: codexGone,
			want:  "",
		},
	} {
		t.Run(tc.name, func(t *testing.T) {
			got := DropStaleEvents([]byte(tc.in), tc.modes)
			if string(got) != tc.want {
				t.Errorf("DropStaleEvents(%q, %+v) = %q, want %q", tc.in, tc.modes, got, tc.want)
			}
		})
	}
}

// The fast path must not copy, since this runs on every byte a person types.
func TestDropStaleEventsDoesNotAllocateWhenNothingIsStale(t *testing.T) {
	in := []byte("\x1b[Ahello\r")
	got := DropStaleEvents(in, codexGone)
	if &got[0] != &in[0] {
		t.Errorf("DropStaleEvents copied a chunk with nothing stale in it")
	}
}

// DropStaleEvents must not modify its input, which would corrupt a caller that also logs the chunk.
func TestDropStaleEventsLeavesItsInputAlone(t *testing.T) {
	in := []byte("ab\x1b[Ocd")
	orig := append([]byte(nil), in...)
	DropStaleEvents(in, codexGone)
	if !bytes.Equal(in, orig) {
		t.Errorf("DropStaleEvents modified its input: got %q, want %q", in, orig)
	}
}

// The form the server actually calls, since ReplyFramer.Split coalesces adjacent non-reply bytes into
// one part: a part can hold several sequences and a keystroke together.
func TestDropStaleParts(t *testing.T) {
	for _, tc := range []struct {
		name  string
		in    []Part
		modes TerminalModes
		want  []Part
	}{
		{
			name:  "a coalesced part is filtered inside, not dropped whole",
			in:    []Part{{Data: []byte("\x1b[100;5:3u\x1b[Ols\r")}},
			modes: codexGone,
			want:  []Part{{Data: []byte("ls\r")}},
		},
		{
			name:  "a part of nothing but stale events is removed",
			in:    []Part{{Data: []byte("\x1b[100;5:3u")}},
			modes: codexGone,
			want:  []Part{},
		},
		{
			// A reply belongs to the query proxy and must not be touched here, whatever the modes say.
			name: "reply parts pass through",
			in: []Part{
				{Data: []byte("\x1b]11;rgb:2828/2c2c/3434\x07"), Reply: true},
				{Data: []byte("\x1b[O")},
				{Data: []byte("\x1b[?0u"), Reply: true},
			},
			modes: codexGone,
			want: []Part{
				{Data: []byte("\x1b]11;rgb:2828/2c2c/3434\x07"), Reply: true},
				{Data: []byte("\x1b[?0u"), Reply: true},
			},
		},
		{
			name:  "nothing dropped while the program is running",
			in:    []Part{{Data: []byte("\x1b[100;5:3u\x1b[O")}},
			modes: codexRunning,
			want:  []Part{{Data: []byte("\x1b[100;5:3u\x1b[O")}},
		},
	} {
		t.Run(tc.name, func(t *testing.T) {
			got := DropStaleParts(tc.in, tc.modes)
			if len(got) != len(tc.want) {
				t.Fatalf("DropStaleParts() = %q, want %q", partStrings(got), partStrings(tc.want))
			}
			for i := range got {
				if string(got[i].Data) != string(tc.want[i].Data) || got[i].Reply != tc.want[i].Reply {
					t.Errorf("DropStaleParts() = %q, want %q", partStrings(got), partStrings(tc.want))
					return
				}
			}
		})
	}
}

// partStrings renders parts for a failure message, since Part holds bytes.
func partStrings(parts []Part) []string {
	out := make([]string, 0, len(parts))
	for _, p := range parts {
		s := string(p.Data)
		if p.Reply {
			s = "reply:" + s
		}
		out = append(out, s)
	}
	return out
}
