package paths

import (
	"path/filepath"
	"strings"
	"testing"
)

func TestValidateSessionName(t *testing.T) {
	tests := []struct {
		name    string
		input   string
		wantErr bool
	}{
		{"simple", "work", false},
		{"kitty style", "kitty.55", false},
		{"dashes and underscores", "my-session_2", false},
		{"digits only", "12345", false},
		{"max length", strings.Repeat("a", MaxSessionNameLen), false},

		{"empty", "", true},
		{"too long", strings.Repeat("a", MaxSessionNameLen+1), true},
		{"dot", ".", true},
		{"dotdot", "..", true},
		{"leading dot", ".hidden", true},
		{"slash", "a/b", true},
		{"traversal", "../../etc/passwd", true},
		{"nul byte", "a\x00b", true},
		{"newline", "a\nb", true},
		{"space", "a b", true},
		{"shell metachar", "a;b", true},
		{"non-ascii", "sesión", true},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			err := ValidateSessionName(tt.input)
			if (err != nil) != tt.wantErr {
				t.Errorf("ValidateSessionName(%q) error = %v, wantErr %v",
					tt.input, err, tt.wantErr)
			}
		})
	}
}

// Any name that survives validation must produce paths inside the intended directories.
// This states the property the validator exists to guarantee: rejection is the only
// thing standing between a hostile name and an arbitrary socket or unlink target, since
// the path helpers themselves do no sanitizing.
func TestValidNamesProduceContainedPaths(t *testing.T) {
	d := Dirs{Runtime: "/run/cm", State: "/state/cm"}

	hostile := []string{"../evil", "a/../../evil", "/etc/passwd", "..", ".", "a\x00b"}
	for _, name := range hostile {
		if err := ValidateSessionName(name); err == nil {
			t.Errorf("ValidateSessionName(%q) = nil, want rejection: it would yield socket %q",
				name, d.ShimSocket(name))
		}
	}

	for _, name := range []string{"work", "kitty.55", "my-session_2"} {
		if err := ValidateSessionName(name); err != nil {
			t.Fatalf("ValidateSessionName(%q) = %v, want nil", name, err)
		}
		for _, got := range []string{d.ShimSocket(name), d.SessionLog(name)} {
			if filepath.Clean(got) != got {
				t.Errorf("path %q for name %q is not already clean", got, name)
			}
			if !strings.HasPrefix(got, "/run/cm/") && !strings.HasPrefix(got, "/state/cm/") {
				t.Errorf("path %q for name %q escapes both dirs", got, name)
			}
		}
	}
}

// An over-long socket path fails at bind with a bare EINVAL, so it is checked up front to
// produce an error that names the limit and suggests a fix.
func TestCheckSocketPath(t *testing.T) {
	if err := CheckSocketPath("/tmp/cm-501/shim-work.sock"); err != nil {
		t.Errorf("CheckSocketPath(short) = %v, want nil", err)
	}

	long := "/" + strings.Repeat("a", MaxSocketPathLen)
	err := CheckSocketPath(long)
	if err == nil {
		t.Fatalf("CheckSocketPath(%d bytes) = nil, want an error", len(long))
	}
	// The message has to be actionable: the failure mode it replaces was an opaque
	// "invalid argument" with no mention of length.
	for _, want := range []string{"limit", Env("RUNTIME_DIR")} {
		if !strings.Contains(err.Error(), want) {
			t.Errorf("error %q does not mention %q", err, want)
		}
	}
}

// A reference is a name unless it carries the sigil, and the sigil cannot appear in a name, so the two
// namespaces cannot overlap however a session is named.
func TestSessionRefSplitsIDsFromNames(t *testing.T) {
	tests := []struct {
		ref      string
		want     string
		wantIsID bool
	}{
		{"work", "work", false},
		{"@a7k2m9x4", "a7k2m9x4", true},
		// A digits-only name stays a name, which is the case the sigil exists for.
		{"7", "7", false},
		{"@7", "7", true},
		// Not special-cased: an empty reference stays empty and its own validator rejects it.
		{"", "", false},
		{"@", "", true},
		// Only the first sigil is the marker, so an ID is never silently rewritten.
		{"@@x", "@x", true},
	}
	for _, tt := range tests {
		got, gotIsID := SessionRef(tt.ref)
		if got != tt.want || gotIsID != tt.wantIsID {
			t.Errorf("SessionRef(%q) = %q, %v, want %q, %v",
				tt.ref, got, gotIsID, tt.want, tt.wantIsID)
		}
	}
}

// The sigil must be unusable in a name, or a name could be mistaken for an ID reference.
func TestValidateSessionNameRejectsTheIDSigil(t *testing.T) {
	if err := ValidateSessionName("work" + IDSigil); err == nil {
		t.Error("ValidateSessionName() accepted a name containing the ID sigil, want rejection")
	}
	if err := ValidateSessionName(IDSigil + "work"); err == nil {
		t.Error("ValidateSessionName() accepted a name starting with the ID sigil, want rejection")
	}
}

func TestValidateSessionID(t *testing.T) {
	valid := []string{"a7k2m9x4", "mig00001", "x", "0"}
	for _, id := range valid {
		if err := ValidateSessionID(id); err != nil {
			t.Errorf("ValidateSessionID(%q) error = %v, want nil", id, err)
		}
	}
	// Anything that could leave the runtime directory or was never generated by cm.
	invalid := []string{"", "../etc/passwd", "a/b", "Work", "a-b", "a.b", "@a7k2m9x4",
		strings.Repeat("a", MaxSessionIDLen+1)}
	for _, id := range invalid {
		if err := ValidateSessionID(id); err == nil {
			t.Errorf("ValidateSessionID(%q) = nil error, want rejection", id)
		}
	}
}
